"""Mirth Connect channel configuration generator (Premium Tier)."""

from __future__ import annotations

import textwrap
from datetime import datetime, timezone

from dicom_hl7_mcp.utils.license import require_premium


def generate_mirth_channel(
    source_type: str,
    destination_type: str,
    use_case: str,
) -> str:
    """Generate a Mirth Connect channel configuration.

    Args:
        source_type: Source data format — "HL7v2", "DICOM", "FHIR", "Database", "File".
        destination_type: Destination data format — "HL7v2", "FHIR", "Database", "File", "HTTP".
        use_case: Description of the integration use case (e.g., "ADT feed from Epic to PACS",
            "Radiology report from RIS to EMR", "Lab order interface").

    Returns:
        Mirth Connect channel XML skeleton with source/destination connectors,
        transformer steps, filter logic, and implementation notes.
    """
    premium_check = require_premium("generate_mirth_channel")
    if premium_check:
        return premium_check

    source_type = source_type.strip().upper()
    destination_type = destination_type.strip().upper()
    use_case = use_case.strip()

    # Normalize types
    source_norm = _normalize_type(source_type)
    dest_norm = _normalize_type(destination_type)

    if source_norm is None:
        return f"Unsupported source type: '{source_type}'. Supported: HL7v2, DICOM, FHIR, Database, File."
    if dest_norm is None:
        return f"Unsupported destination type: '{destination_type}'. Supported: HL7v2, FHIR, Database, File, HTTP."

    # Generate channel name
    channel_name = _generate_channel_name(source_norm, dest_norm, use_case)

    # Build the channel XML
    xml = _build_channel_xml(channel_name, source_norm, dest_norm, use_case)

    # Build implementation notes
    notes = _build_implementation_notes(source_norm, dest_norm, use_case)

    return f"{xml}\n\n{notes}"


def _normalize_type(type_str: str) -> str | None:
    """Normalize the connector type."""
    mapping = {
        "HL7V2": "HL7v2",
        "HL7": "HL7v2",
        "HL7 V2": "HL7v2",
        "V2": "HL7v2",
        "DICOM": "DICOM",
        "FHIR": "FHIR",
        "FHIR R4": "FHIR",
        "DATABASE": "Database",
        "DB": "Database",
        "SQL": "Database",
        "FILE": "File",
        "FILESYSTEM": "File",
        "HTTP": "HTTP",
        "REST": "HTTP",
        "API": "HTTP",
    }
    return mapping.get(type_str)


def _generate_channel_name(source: str, dest: str, use_case: str) -> str:
    """Generate a descriptive channel name."""
    # Extract key words from use case
    words = use_case.lower().split()
    key_terms = [w for w in words if w in (
        "adt", "orm", "oru", "mdm", "dft", "siu", "bar", "radiology", "lab",
        "order", "result", "report", "admit", "discharge", "transfer", "merge",
        "schedule", "charge", "demographics", "worklist",
    )]
    suffix = "_".join(key_terms[:3]) if key_terms else "interface"
    return f"{source}_to_{dest}_{suffix}"


def _build_channel_xml(name: str, source: str, dest: str, use_case: str) -> str:
    """Build the Mirth Connect channel XML."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S.000Z")

    source_connector = _get_source_connector_xml(source)
    dest_connector = _get_destination_connector_xml(dest)
    transformer_steps = _get_transformer_xml(source, dest, use_case)
    filter_rules = _get_filter_xml(source, use_case)

    xml = textwrap.dedent(f"""\
    <!-- Mirth Connect Channel Configuration -->
    <!-- Generated by DICOM/HL7 Developer AI Assistant -->
    <!-- Use Case: {use_case} -->
    <!-- Source: {source} | Destination: {dest} -->
    <!-- Generated: {now} -->

    <channel version="4.4.0">
      <id>GENERATE-NEW-UUID</id>
      <nextMetaDataId>2</nextMetaDataId>
      <name>{name}</name>
      <description>{use_case}</description>
      <enabled>true</enabled>
      <lastModified>
        <time>{now}</time>
        <timezone>UTC</timezone>
      </lastModified>
      <revision>1</revision>

      <sourceConnector version="4.4.0">
        <metaDataId>0</metaDataId>
        <name>sourceConnector</name>
        <properties class="{_get_source_class(source)}">
{textwrap.indent(source_connector, '          ')}
        </properties>
        <transformer version="4.4.0">
          <elements>
{textwrap.indent(transformer_steps, '            ')}
          </elements>
          <inboundDataType>{_get_data_type(source)}</inboundDataType>
          <outboundDataType>{_get_data_type(dest)}</outboundDataType>
          <inboundProperties class="{_get_data_type_props(source)}"/>
          <outboundProperties class="{_get_data_type_props(dest)}"/>
        </transformer>
        <filter version="4.4.0">
          <elements>
{textwrap.indent(filter_rules, '            ')}
          </elements>
        </filter>
        <transportName>{_get_transport_name(source)}</transportName>
        <mode>SOURCE</mode>
        <enabled>true</enabled>
      </sourceConnector>

      <destinationConnectors>
        <connector version="4.4.0">
          <metaDataId>1</metaDataId>
          <name>Destination</name>
          <properties class="{_get_dest_class(dest)}">
{textwrap.indent(dest_connector, '            ')}
          </properties>
          <transformer version="4.4.0">
            <elements/>
            <inboundDataType>{_get_data_type(dest)}</inboundDataType>
            <outboundDataType>{_get_data_type(dest)}</outboundDataType>
          </transformer>
          <transportName>{_get_transport_name(dest)}</transportName>
          <mode>DESTINATION</mode>
          <enabled>true</enabled>
          <waitForPrevious>true</waitForPrevious>
        </connector>
      </destinationConnectors>

      <preprocessingScript>// Preprocessing script runs before the message enters the channel
    // Add any pre-processing logic here (e.g., character encoding fixes)
    return message;</preprocessingScript>

      <postprocessingScript>// Post-processing script runs after all destinations complete
    // Add any post-processing logic here (e.g., audit logging)
    return;</postprocessingScript>

      <deployScript>// Runs when channel is deployed
    logger.info("Channel {name} deployed successfully.");
    return;</deployScript>

      <undeployScript>// Runs when channel is undeployed
    logger.info("Channel {name} undeployed.");
    return;</undeployScript>

      <properties version="4.4.0">
        <clearGlobalChannelMap>true</clearGlobalChannelMap>
        <messageStorageMode>DEVELOPMENT</messageStorageMode>
        <encryptData>false</encryptData>
        <initialState>STARTED</initialState>
        <storeAttachments>true</storeAttachments>
        <tags/>
        <metaDataColumns/>
        <archiveEnabled>true</archiveEnabled>
      </properties>
    </channel>""")

    return xml


def _get_source_class(source: str) -> str:
    classes = {
        "HL7v2": "com.mirth.connect.connectors.tcp.TcpReceiverProperties",
        "DICOM": "com.mirth.connect.connectors.dimse.DICOMReceiverProperties",
        "FHIR": "com.mirth.connect.connectors.http.HttpReceiverProperties",
        "Database": "com.mirth.connect.connectors.jdbc.DatabaseReceiverProperties",
        "File": "com.mirth.connect.connectors.file.FileReceiverProperties",
    }
    return classes.get(source, "com.mirth.connect.connectors.tcp.TcpReceiverProperties")


def _get_dest_class(dest: str) -> str:
    classes = {
        "HL7v2": "com.mirth.connect.connectors.tcp.TcpDispatcherProperties",
        "FHIR": "com.mirth.connect.connectors.http.HttpDispatcherProperties",
        "Database": "com.mirth.connect.connectors.jdbc.DatabaseDispatcherProperties",
        "File": "com.mirth.connect.connectors.file.FileDispatcherProperties",
        "HTTP": "com.mirth.connect.connectors.http.HttpDispatcherProperties",
        "DICOM": "com.mirth.connect.connectors.dimse.DICOMDispatcherProperties",
    }
    return classes.get(dest, "com.mirth.connect.connectors.tcp.TcpDispatcherProperties")


def _get_transport_name(connector_type: str) -> str:
    names = {
        "HL7v2": "TCP Listener",
        "DICOM": "DICOM Listener",
        "FHIR": "HTTP Listener",
        "Database": "Database Reader",
        "File": "File Reader",
        "HTTP": "HTTP Sender",
    }
    return names.get(connector_type, "TCP Listener")


def _get_data_type(connector_type: str) -> str:
    types = {
        "HL7v2": "HL7V2",
        "DICOM": "DICOM",
        "FHIR": "JSON",
        "Database": "XML",
        "File": "RAW",
        "HTTP": "JSON",
    }
    return types.get(connector_type, "RAW")


def _get_data_type_props(connector_type: str) -> str:
    props = {
        "HL7v2": "com.mirth.connect.plugins.datatypes.hl7v2.HL7v2DataTypeProperties",
        "DICOM": "com.mirth.connect.plugins.datatypes.dicom.DICOMDataTypeProperties",
        "FHIR": "com.mirth.connect.plugins.datatypes.json.JSONDataTypeProperties",
        "Database": "com.mirth.connect.plugins.datatypes.xml.XMLDataTypeProperties",
        "File": "com.mirth.connect.plugins.datatypes.raw.RawDataTypeProperties",
        "HTTP": "com.mirth.connect.plugins.datatypes.json.JSONDataTypeProperties",
    }
    return props.get(connector_type, "com.mirth.connect.plugins.datatypes.raw.RawDataTypeProperties")


def _get_source_connector_xml(source: str) -> str:
    """Generate source connector properties XML."""
    if source == "HL7v2":
        return textwrap.dedent("""\
        <!-- TCP Listener for HL7v2 over MLLP -->
        <listenerConnectorProperties version="4.4.0">
          <host>0.0.0.0</host>
          <port>6661</port>  <!-- CHANGE: Set your listener port -->
        </listenerConnectorProperties>
        <serverMode>true</serverMode>
        <remoteAddress></remoteAddress>
        <remotePort></remotePort>
        <overrideLocalBinding>false</overrideLocalBinding>
        <receiveTimeout>0</receiveTimeout>
        <bufferSize>65536</bufferSize>
        <maxConnections>10</maxConnections>
        <keepConnectionOpen>true</keepConnectionOpen>
        <dataTypeBinary>false</dataTypeBinary>
        <charsetEncoding>DEFAULT_ENCODING</charsetEncoding>
        <respondOnNewConnection>0</respondOnNewConnection>
        <responseAddress></responseAddress>
        <responsePort></responsePort>
        <!-- MLLP Transmission Mode -->
        <transmissionModeProperties class="com.mirth.connect.plugins.mllpmode.MLLPModeProperties">
          <pluginPointName>MLLP</pluginPointName>
          <startOfMessageBytes>0B</startOfMessageBytes>
          <endOfMessageBytes>1C0D</endOfMessageBytes>
          <useMLLPv2>false</useMLLPv2>
        </transmissionModeProperties>""")
    elif source == "DICOM":
        return textwrap.dedent("""\
        <!-- DICOM Listener -->
        <listenerConnectorProperties version="4.4.0">
          <host>0.0.0.0</host>
          <port>11112</port>  <!-- CHANGE: Set your DICOM listener port -->
        </listenerConnectorProperties>
        <applicationEntity>MIRTH_AE</applicationEntity>  <!-- CHANGE: Set your AE Title -->
        <localHost></localHost>
        <localPort></localPort>
        <localApplicationEntity></localApplicationEntity>
        <soCloseDelay>50</soCloseDelay>
        <releaseTo>5</releaseTo>
        <requestTo>5</requestTo>
        <idleTo>60</idleTo>
        <acceptTo>5000</acceptTo>
        <async>0</async>""")
    elif source == "FHIR":
        return textwrap.dedent("""\
        <!-- HTTP Listener for FHIR REST API -->
        <listenerConnectorProperties version="4.4.0">
          <host>0.0.0.0</host>
          <port>8080</port>  <!-- CHANGE: Set your HTTP listener port -->
        </listenerConnectorProperties>
        <contextPath>/fhir</contextPath>  <!-- CHANGE: Set your context path -->
        <timeout>30000</timeout>
        <binaryMimeTypes>application/fhir+json,application/json</binaryMimeTypes>
        <binaryMimeTypesRegex>false</binaryMimeTypesRegex>
        <responseContentType>application/fhir+json</responseContentType>
        <responseStatusCode></responseStatusCode>""")
    elif source == "Database":
        return textwrap.dedent("""\
        <!-- Database Reader -->
        <driver>org.postgresql.Driver</driver>  <!-- CHANGE: Set your DB driver -->
        <url>jdbc:postgresql://localhost:5432/mydb</url>  <!-- CHANGE: Set your DB URL -->
        <username>CHANGE_ME</username>
        <password>CHANGE_ME</password>
        <select>
          <!-- CHANGE: Set your polling query -->
          SELECT * FROM outbound_queue WHERE processed = false ORDER BY created_at LIMIT 100
        </select>
        <update>
          <!-- CHANGE: Set your post-read update query -->
          UPDATE outbound_queue SET processed = true WHERE id = ${resultMap.get('id')}
        </update>
        <pollingType>INTERVAL</pollingType>
        <pollingFrequency>5000</pollingFrequency>
        <retryCount>3</retryCount>""")
    elif source == "File":
        return textwrap.dedent("""\
        <!-- File Reader -->
        <scheme>FILE</scheme>
        <host>C:/hl7/inbound</host>  <!-- CHANGE: Set your input directory -->
        <fileFilter>*.hl7</fileFilter>  <!-- CHANGE: Set your file filter -->
        <regex>false</regex>
        <directoryRecursion>false</directoryRecursion>
        <ignoreDot>true</ignoreDot>
        <anonymous>false</anonymous>
        <pollingType>INTERVAL</pollingType>
        <pollingFrequency>1000</pollingFrequency>
        <afterProcessingAction>MOVE</afterProcessingAction>
        <moveToDirectory>C:/hl7/processed</moveToDirectory>  <!-- CHANGE -->
        <moveToFileName></moveToFileName>
        <errorMoveToDirectory>C:/hl7/error</errorMoveToDirectory>  <!-- CHANGE -->
        <checkFileAge>true</checkFileAge>
        <fileAge>1000</fileAge>
        <sortBy>date</sortBy>
        <charsetEncoding>DEFAULT_ENCODING</charsetEncoding>""")
    return "<!-- Configure source connector -->"


def _get_destination_connector_xml(dest: str) -> str:
    """Generate destination connector properties XML."""
    if dest == "HL7v2":
        return textwrap.dedent("""\
        <!-- TCP Sender for HL7v2 over MLLP -->
        <remoteAddress>DESTINATION_HOST</remoteAddress>  <!-- CHANGE -->
        <remotePort>6662</remotePort>  <!-- CHANGE -->
        <overrideLocalBinding>false</overrideLocalBinding>
        <localAddress></localAddress>
        <localPort></localPort>
        <sendTimeout>10000</sendTimeout>
        <bufferSize>65536</bufferSize>
        <maxConnections>10</maxConnections>
        <keepConnectionOpen>true</keepConnectionOpen>
        <charsetEncoding>DEFAULT_ENCODING</charsetEncoding>
        <dataTypeBinary>false</dataTypeBinary>
        <queueConnectorProperties version="4.4.0">
          <queueEnabled>true</queueEnabled>
          <sendFirst>false</sendFirst>
          <retryIntervalMillis>10000</retryIntervalMillis>
          <regenerateTemplate>false</regenerateTemplate>
          <retryCount>0</retryCount>
          <rotate>false</rotate>
          <includeFilteredDestinations>false</includeFilteredDestinations>
          <threadCount>1</threadCount>
        </queueConnectorProperties>
        <transmissionModeProperties class="com.mirth.connect.plugins.mllpmode.MLLPModeProperties">
          <pluginPointName>MLLP</pluginPointName>
          <startOfMessageBytes>0B</startOfMessageBytes>
          <endOfMessageBytes>1C0D</endOfMessageBytes>
          <useMLLPv2>false</useMLLPv2>
        </transmissionModeProperties>""")
    elif dest == "FHIR" or dest == "HTTP":
        return textwrap.dedent("""\
        <!-- HTTP Sender for FHIR/REST -->
        <host>https://fhir-server.example.com/fhir</host>  <!-- CHANGE -->
        <useProxyServer>false</useProxyServer>
        <method>POST</method>
        <headers>
          <entry>
            <string>Content-Type</string>
            <list><string>application/fhir+json</string></list>
          </entry>
          <entry>
            <string>Authorization</string>
            <list><string>Bearer YOUR_TOKEN_HERE</string></list>  <!-- CHANGE -->
          </entry>
        </headers>
        <parameters/>
        <responseXmlBody>false</responseXmlBody>
        <responseParseMultipart>true</responseParseMultipart>
        <useHeadersVariable>false</useHeadersVariable>
        <useParametersVariable>false</useParametersVariable>
        <multipart>false</multipart>
        <socketTimeout>30000</socketTimeout>
        <connectTimeout>5000</connectTimeout>
        <charset>UTF-8</charset>
        <queueConnectorProperties version="4.4.0">
          <queueEnabled>true</queueEnabled>
          <retryIntervalMillis>10000</retryIntervalMillis>
          <retryCount>3</retryCount>
        </queueConnectorProperties>""")
    elif dest == "Database":
        return textwrap.dedent("""\
        <!-- Database Writer -->
        <driver>org.postgresql.Driver</driver>  <!-- CHANGE -->
        <url>jdbc:postgresql://localhost:5432/mydb</url>  <!-- CHANGE -->
        <username>CHANGE_ME</username>
        <password>CHANGE_ME</password>
        <query>
          <!-- CHANGE: Set your INSERT/UPDATE query -->
          INSERT INTO hl7_messages (
            message_type, patient_id, patient_name, accession_number,
            message_datetime, raw_message, created_at
          ) VALUES (
            ${msg['MSH']['MSH.9']['MSH.9.1']},
            ${msg['PID']['PID.3']['PID.3.1']},
            ${msg['PID']['PID.5']['PID.5.1']},
            ${msg['OBR']['OBR.3']['OBR.3.1']},
            NOW(),
            ${connectorMessage.getRawData()},
            NOW()
          )
        </query>""")
    elif dest == "File":
        return textwrap.dedent("""\
        <!-- File Writer -->
        <scheme>FILE</scheme>
        <host>C:/hl7/outbound</host>  <!-- CHANGE: Set your output directory -->
        <outputPattern>${message.encodedData}_${date:yyyyMMddHHmmssSSS}.hl7</outputPattern>
        <anonymous>false</anonymous>
        <charsetEncoding>DEFAULT_ENCODING</charsetEncoding>
        <outputAppend>false</outputAppend>
        <errorOnExists>false</errorOnExists>
        <temporary>false</temporary>""")
    return "<!-- Configure destination connector -->"


def _get_transformer_xml(source: str, dest: str, use_case: str) -> str:
    """Generate transformer steps based on the use case."""
    use_lower = use_case.lower()

    steps = []

    if "adt" in use_lower or "admit" in use_lower or "demographic" in use_lower:
        steps.append(_make_transformer_step(
            "Extract Patient Demographics",
            textwrap.dedent("""\
            // Extract key patient demographics
            var patientId = msg['PID']['PID.3']['PID.3.1'].toString();
            var patientName = msg['PID']['PID.5']['PID.5.1'].toString() + '^' +
                              msg['PID']['PID.5']['PID.5.2'].toString();
            var dob = msg['PID']['PID.7']['PID.7.1'].toString();
            var sex = msg['PID']['PID.8']['PID.8.1'].toString();
            var patientClass = msg['PV1']['PV1.2']['PV1.2.1'].toString();

            channelMap.put('patientId', patientId);
            channelMap.put('patientName', patientName);
            channelMap.put('dob', dob);
            channelMap.put('sex', sex);
            channelMap.put('patientClass', patientClass);

            logger.info('Processing ADT for patient: ' + patientId);"""),
            0,
        ))

    if "order" in use_lower or "orm" in use_lower:
        steps.append(_make_transformer_step(
            "Extract Order Information",
            textwrap.dedent("""\
            // Extract order details
            var accessionNumber = msg['OBR']['OBR.3']['OBR.3.1'].toString();
            var orderControl = msg['ORC']['ORC.1']['ORC.1.1'].toString();
            var procedureCode = msg['OBR']['OBR.4']['OBR.4.1'].toString();
            var procedureDesc = msg['OBR']['OBR.4']['OBR.4.2'].toString();
            var orderingProvider = msg['ORC']['ORC.12']['ORC.12.1'].toString();
            var clinicalHistory = msg['OBR']['OBR.13']['OBR.13.1'].toString();

            channelMap.put('accessionNumber', accessionNumber);
            channelMap.put('orderControl', orderControl);
            channelMap.put('procedureCode', procedureCode);
            channelMap.put('procedureDesc', procedureDesc);

            logger.info('Processing order ' + orderControl + ' for accession: ' + accessionNumber);"""),
            0,
        ))

    if "result" in use_lower or "oru" in use_lower or "report" in use_lower:
        steps.append(_make_transformer_step(
            "Extract Result/Report Information",
            textwrap.dedent("""\
            // Extract result details
            var accessionNumber = msg['OBR']['OBR.3']['OBR.3.1'].toString();
            var resultStatus = msg['OBR']['OBR.25']['OBR.25.1'].toString();
            var readingPhysician = msg['OBR']['OBR.32']['OBR.32.1'].toString();

            // Build report text from OBX segments
            var reportText = '';
            for each (var obx in msg['OBX']) {
                if (obx['OBX.2']['OBX.2.1'].toString() == 'FT' ||
                    obx['OBX.2']['OBX.2.1'].toString() == 'TX') {
                    reportText += obx['OBX.5']['OBX.5.1'].toString() + '\\n';
                }
            }

            channelMap.put('accessionNumber', accessionNumber);
            channelMap.put('resultStatus', resultStatus);
            channelMap.put('reportText', reportText);

            logger.info('Processing result status=' + resultStatus + ' for: ' + accessionNumber);"""),
            0,
        ))

    if dest == "FHIR":
        steps.append(_make_transformer_step(
            "Transform to FHIR Bundle",
            textwrap.dedent("""\
            // Transform HL7v2 to FHIR R4 Bundle
            // NOTE: This is a skeleton. Customize the mapping for your specific use case.
            var bundle = {
                "resourceType": "Bundle",
                "type": "transaction",
                "entry": []
            };

            // Create Patient resource from PID
            var patient = {
                "resourceType": "Patient",
                "identifier": [{
                    "system": "urn:oid:YOUR_MRN_OID",  // CHANGE
                    "value": msg['PID']['PID.3']['PID.3.1'].toString()
                }],
                "name": [{
                    "family": msg['PID']['PID.5']['PID.5.1'].toString(),
                    "given": [msg['PID']['PID.5']['PID.5.2'].toString()]
                }],
                "gender": mapGender(msg['PID']['PID.8']['PID.8.1'].toString()),
                "birthDate": formatFhirDate(msg['PID']['PID.7']['PID.7.1'].toString())
            };

            bundle.entry.push({
                "resource": patient,
                "request": { "method": "PUT", "url": "Patient?identifier=" + patient.identifier[0].value }
            });

            // Helper functions
            function mapGender(hl7Sex) {
                var map = {'M': 'male', 'F': 'female', 'O': 'other', 'U': 'unknown'};
                return map[hl7Sex] || 'unknown';
            }

            function formatFhirDate(hl7Date) {
                if (hl7Date.length >= 8) {
                    return hl7Date.substring(0,4) + '-' + hl7Date.substring(4,6) + '-' + hl7Date.substring(6,8);
                }
                return hl7Date;
            }

            // Set the transformed message
            tmp = JSON.stringify(bundle, null, 2);"""),
            1,
        ))

    if not steps:
        steps.append(_make_transformer_step(
            "Default Transformer",
            textwrap.dedent("""\
            // Add your transformation logic here
            // Access HL7 fields: msg['PID']['PID.3']['PID.3.1'].toString()
            // Set channel variables: channelMap.put('key', value)
            // Log: logger.info('message')
            logger.info('Processing message: ' + msg['MSH']['MSH.10']['MSH.10.1'].toString());"""),
            0,
        ))

    return "\n".join(steps)


def _make_transformer_step(name: str, script: str, sequence: int) -> str:
    """Create a transformer step XML element."""
    return textwrap.dedent(f"""\
    <com.mirth.connect.plugins.javascriptstep.JavaScriptStep version="4.4.0">
      <name>{name}</name>
      <sequenceNumber>{sequence}</sequenceNumber>
      <enabled>true</enabled>
      <script>{script}</script>
    </com.mirth.connect.plugins.javascriptstep.JavaScriptStep>""")


def _get_filter_xml(source: str, use_case: str) -> str:
    """Generate filter rules."""
    use_lower = use_case.lower()

    if "adt" in use_lower:
        return textwrap.dedent("""\
        <com.mirth.connect.plugins.javascriptrule.JavaScriptRule version="4.4.0">
          <name>Filter ADT Event Types</name>
          <sequenceNumber>0</sequenceNumber>
          <enabled>true</enabled>
          <script>
        // Only process relevant ADT events
        // CHANGE: Adjust the accepted event types for your use case
        var eventType = msg['MSH']['MSH.9']['MSH.9.2'].toString();
        var acceptedEvents = ['A01', 'A02', 'A03', 'A04', 'A08', 'A34', 'A40'];

        if (acceptedEvents.indexOf(eventType) === -1) {
            logger.info('Filtering out ADT event: ' + eventType);
            return false;  // Filter out (do not process)
        }

        return true;  // Accept message
          </script>
        </com.mirth.connect.plugins.javascriptrule.JavaScriptRule>""")

    if "result" in use_lower or "oru" in use_lower or "report" in use_lower:
        return textwrap.dedent("""\
        <com.mirth.connect.plugins.javascriptrule.JavaScriptRule version="4.4.0">
          <name>Filter Result Status</name>
          <sequenceNumber>0</sequenceNumber>
          <enabled>true</enabled>
          <script>
        // Only forward final and corrected results
        // CHANGE: Adjust accepted statuses for your use case
        var resultStatus = msg['OBR']['OBR.25']['OBR.25.1'].toString();
        var acceptedStatuses = ['F', 'C', 'P'];  // Final, Corrected, Preliminary

        if (acceptedStatuses.indexOf(resultStatus) === -1) {
            logger.info('Filtering out result with status: ' + resultStatus);
            return false;
        }

        return true;
          </script>
        </com.mirth.connect.plugins.javascriptrule.JavaScriptRule>""")

    return "<!-- Add filter rules as needed -->"


def _build_implementation_notes(source: str, dest: str, use_case: str) -> str:
    """Build implementation notes for the channel."""
    parts = [
        "=" * 70,
        "IMPLEMENTATION NOTES",
        "=" * 70,
        "",
        "1. BEFORE DEPLOYING:",
        "   - Replace all 'CHANGE' placeholders with actual values",
        "   - Generate a unique UUID for the channel ID",
        "   - Set the correct host/port for source and destination",
        "   - Configure authentication credentials",
        "   - Test with sample messages in a non-production environment",
        "",
        "2. SECURITY CONSIDERATIONS:",
        "   - Use TLS for all network connections",
        "   - Store credentials in Mirth's configuration map, not in channel XML",
        "   - Implement access controls on Mirth Connect server",
        "   - Enable audit logging for PHI-bearing channels",
        "",
        "3. ERROR HANDLING:",
        "   - Enable queuing on the destination for reliability",
        "   - Configure appropriate retry intervals",
        "   - Set up error alerts in Mirth Connect",
        "   - Monitor the channel dashboard for failed messages",
        "",
        "4. TESTING CHECKLIST:",
        "   - [ ] Test with valid sample messages",
        "   - [ ] Test with malformed messages (error handling)",
        "   - [ ] Test connection failure/recovery",
        "   - [ ] Verify acknowledgment (ACK) handling",
        "   - [ ] Load test with expected message volume",
        "   - [ ] Verify data integrity end-to-end",
        "",
    ]

    if source == "HL7v2" and dest == "HL7v2":
        parts.extend([
            "5. HL7v2 to HL7v2 SPECIFIC:",
            "   - Ensure MLLP framing is correct on both ends",
            "   - Verify HL7 version compatibility",
            "   - Map field differences between sending and receiving systems",
            "   - Handle ACK responses (check for AA/AE/AR)",
            "",
        ])

    if dest == "FHIR":
        parts.extend([
            "5. FHIR SPECIFIC:",
            "   - Use Transaction Bundles for atomic operations",
            "   - Handle FHIR server responses (check OperationOutcome for errors)",
            "   - Implement proper FHIR resource references",
            "   - Use conditional create/update to prevent duplicates",
            "   - Consider FHIR Subscription for real-time notifications",
            "",
        ])

    return "\n".join(parts)
