"""
HL7 v2-to-FHIR R4 mappings and DICOM-to-HL7 field mappings.

Based on the HL7 v2-to-FHIR Implementation Guide (http://hl7.org/fhir/uv/v2mappings/)
and IHE Technical Framework for DICOM-to-HL7 mapping.

Reference: HL7 FHIR R4 (4.0.1), HL7 v2-to-FHIR IG (STU1)
"""

# ---------------------------------------------------------------
# HL7 v2 to FHIR R4 Mappings
# ---------------------------------------------------------------
# Key: (segment, field_position) or (segment, field_position, component)
# Value: {
#   "fhir_resource": str,
#   "fhir_path": str,
#   "fhir_element_type": str,
#   "notes": str,
#   "conversion_type": str (direct|transform|lookup|complex),
#   "concept_map": str | None  (ConceptMap reference if applicable)
# }

HL7_TO_FHIR_MAP: dict[tuple, dict] = {
    # ---------------------------------------------------------------
    # MSH -> MessageHeader
    # ---------------------------------------------------------------
    ("MSH", 3): {
        "fhir_resource": "MessageHeader",
        "fhir_path": "MessageHeader.source.name",
        "fhir_element_type": "string",
        "notes": "MSH-3 (Sending Application) maps to the source element of MessageHeader.",
        "conversion_type": "direct",
        "concept_map": None,
    },
    ("MSH", 4): {
        "fhir_resource": "MessageHeader",
        "fhir_path": "MessageHeader.source.endpoint",
        "fhir_element_type": "url",
        "notes": "MSH-4 (Sending Facility) maps to the source endpoint. May need to construct a URL from the HD data type.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("MSH", 5): {
        "fhir_resource": "MessageHeader",
        "fhir_path": "MessageHeader.destination.name",
        "fhir_element_type": "string",
        "notes": "MSH-5 (Receiving Application) maps to destination name.",
        "conversion_type": "direct",
        "concept_map": None,
    },
    ("MSH", 6): {
        "fhir_resource": "MessageHeader",
        "fhir_path": "MessageHeader.destination.endpoint",
        "fhir_element_type": "url",
        "notes": "MSH-6 (Receiving Facility) maps to destination endpoint.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("MSH", 7): {
        "fhir_resource": "Bundle",
        "fhir_path": "Bundle.timestamp",
        "fhir_element_type": "instant",
        "notes": "MSH-7 (Date/Time of Message) maps to Bundle timestamp. Convert HL7 TS to FHIR instant format.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("MSH", 9): {
        "fhir_resource": "MessageHeader",
        "fhir_path": "MessageHeader.eventCoding",
        "fhir_element_type": "Coding",
        "notes": "MSH-9 (Message Type) maps to eventCoding. Use system='http://terminology.hl7.org/CodeSystem/v2-0003' for the trigger event.",
        "conversion_type": "transform",
        "concept_map": "message-type-to-event",
    },
    ("MSH", 10): {
        "fhir_resource": "Bundle",
        "fhir_path": "Bundle.identifier.value",
        "fhir_element_type": "string",
        "notes": "MSH-10 (Message Control ID) becomes the Bundle identifier.",
        "conversion_type": "direct",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # PID -> Patient
    # ---------------------------------------------------------------
    ("PID", 3): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.identifier",
        "fhir_element_type": "Identifier",
        "notes": "PID-3 (Patient Identifier List) maps to Patient.identifier (repeating). CX.1->Identifier.value, CX.4->Identifier.system, CX.5->Identifier.type.coding.code (HL7 Table 0203). Use 'http://terminology.hl7.org/CodeSystem/v2-0203' for the type coding system.",
        "conversion_type": "complex",
        "concept_map": "identifier-type",
    },
    ("PID", 5): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.name",
        "fhir_element_type": "HumanName",
        "notes": "PID-5 (Patient Name) maps to Patient.name. XPN.1->HumanName.family, XPN.2->HumanName.given[0], XPN.3->HumanName.given[1] (middle), XPN.4->HumanName.suffix, XPN.5->HumanName.prefix, XPN.7->HumanName.use (map via Table 0200: L->official, A->usual, M->maiden).",
        "conversion_type": "complex",
        "concept_map": "name-type",
    },
    ("PID", 7): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.birthDate",
        "fhir_element_type": "date",
        "notes": "PID-7 (Date/Time of Birth) maps to Patient.birthDate. Convert YYYYMMDD to YYYY-MM-DD.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("PID", 8): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.gender",
        "fhir_element_type": "code",
        "notes": "PID-8 (Administrative Sex) maps to Patient.gender. Mapping: F->female, M->male, O->other, U->unknown, A->other, N->unknown.",
        "conversion_type": "lookup",
        "concept_map": "administrative-gender",
    },
    ("PID", 10): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.extension[us-core-race]",
        "fhir_element_type": "Extension",
        "notes": "PID-10 (Race) maps to US Core Race extension (http://hl7.org/fhir/us/core/StructureDefinition/us-core-race). US-specific.",
        "conversion_type": "complex",
        "concept_map": "race",
    },
    ("PID", 11): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.address",
        "fhir_element_type": "Address",
        "notes": "PID-11 (Patient Address) maps to Patient.address. XAD.1->Address.line[0], XAD.2->Address.line[1], XAD.3->Address.city, XAD.4->Address.state, XAD.5->Address.postalCode, XAD.6->Address.country, XAD.7->Address.use/type.",
        "conversion_type": "complex",
        "concept_map": "address-type",
    },
    ("PID", 13): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.telecom",
        "fhir_element_type": "ContactPoint",
        "notes": "PID-13 (Phone Number - Home) maps to Patient.telecom with use='home'. XTN components map to ContactPoint.value and ContactPoint.system.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PID", 14): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.telecom",
        "fhir_element_type": "ContactPoint",
        "notes": "PID-14 (Phone Number - Business) maps to Patient.telecom with use='work'.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PID", 15): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.communication.language",
        "fhir_element_type": "CodeableConcept",
        "notes": "PID-15 (Primary Language) maps to Patient.communication.language with preferred=true.",
        "conversion_type": "lookup",
        "concept_map": "language",
    },
    ("PID", 16): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.maritalStatus",
        "fhir_element_type": "CodeableConcept",
        "notes": "PID-16 (Marital Status) maps to Patient.maritalStatus. Use system='http://terminology.hl7.org/CodeSystem/v3-MaritalStatus'. Map: S->S, M->M, D->D, W->W, etc.",
        "conversion_type": "lookup",
        "concept_map": "marital-status",
    },
    ("PID", 18): {
        "fhir_resource": "Account",
        "fhir_path": "Account.identifier",
        "fhir_element_type": "Identifier",
        "notes": "PID-18 (Patient Account Number) maps to Account.identifier. The Account resource is linked to the Patient via Account.subject.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PID", 22): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.extension[us-core-ethnicity]",
        "fhir_element_type": "Extension",
        "notes": "PID-22 (Ethnic Group) maps to US Core Ethnicity extension. US-specific.",
        "conversion_type": "complex",
        "concept_map": "ethnicity",
    },
    ("PID", 29): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.deceasedDateTime",
        "fhir_element_type": "dateTime",
        "notes": "PID-29 (Patient Death Date and Time) maps to Patient.deceasedDateTime.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("PID", 30): {
        "fhir_resource": "Patient",
        "fhir_path": "Patient.deceasedBoolean",
        "fhir_element_type": "boolean",
        "notes": "PID-30 (Patient Death Indicator) maps to Patient.deceasedBoolean when PID-29 is absent. Y->true, N->false.",
        "conversion_type": "transform",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # PV1 -> Encounter
    # ---------------------------------------------------------------
    ("PV1", 2): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.class",
        "fhir_element_type": "Coding",
        "notes": "PV1-2 (Patient Class) maps to Encounter.class. Mapping: I->IMP (inpatient), O->AMB (ambulatory), E->EMER (emergency), P->PRENC (pre-admission). Use system='http://terminology.hl7.org/CodeSystem/v3-ActCode'.",
        "conversion_type": "lookup",
        "concept_map": "encounter-class",
    },
    ("PV1", 3): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.location",
        "fhir_element_type": "Encounter.location",
        "notes": "PV1-3 (Assigned Patient Location) maps to Encounter.location.location (reference to Location resource). PL components become Location resource attributes.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PV1", 4): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.type",
        "fhir_element_type": "CodeableConcept",
        "notes": "PV1-4 (Admission Type) contributes to Encounter.type.",
        "conversion_type": "lookup",
        "concept_map": "admission-type",
    },
    ("PV1", 7): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.participant[attender]",
        "fhir_element_type": "Encounter.participant",
        "notes": "PV1-7 (Attending Doctor) maps to Encounter.participant with type='ATND'. Reference to Practitioner resource.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PV1", 8): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.participant[referrer]",
        "fhir_element_type": "Encounter.participant",
        "notes": "PV1-8 (Referring Doctor) maps to Encounter.participant with type='REF'. Also populates ServiceRequest.requester for imaging orders.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PV1", 17): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.participant[admitter]",
        "fhir_element_type": "Encounter.participant",
        "notes": "PV1-17 (Admitting Doctor) maps to Encounter.participant with type='ADM'.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PV1", 19): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.identifier",
        "fhir_element_type": "Identifier",
        "notes": "PV1-19 (Visit Number) maps to Encounter.identifier with type='VN'.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("PV1", 36): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.hospitalization.dischargeDisposition",
        "fhir_element_type": "CodeableConcept",
        "notes": "PV1-36 (Discharge Disposition) maps to discharge disposition.",
        "conversion_type": "lookup",
        "concept_map": "discharge-disposition",
    },
    ("PV1", 44): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.period.start",
        "fhir_element_type": "dateTime",
        "notes": "PV1-44 (Admit Date/Time) maps to Encounter.period.start.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("PV1", 45): {
        "fhir_resource": "Encounter",
        "fhir_path": "Encounter.period.end",
        "fhir_element_type": "dateTime",
        "notes": "PV1-45 (Discharge Date/Time) maps to Encounter.period.end.",
        "conversion_type": "transform",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # ORC/OBR -> ServiceRequest (Orders)
    # ---------------------------------------------------------------
    ("ORC", 1): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.status",
        "fhir_element_type": "code",
        "notes": "ORC-1 (Order Control) combined with ORC-5 (Order Status) determines ServiceRequest.status. NW->active, CA->revoked, DC->revoked, HD->on-hold, SC->active. See v2-to-FHIR IG for complete mapping.",
        "conversion_type": "complex",
        "concept_map": "order-control-to-request-status",
    },
    ("ORC", 2): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.identifier[placer]",
        "fhir_element_type": "Identifier",
        "notes": "ORC-2 (Placer Order Number) maps to ServiceRequest.identifier with type='PLAC'.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("ORC", 3): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.identifier[filler]",
        "fhir_element_type": "Identifier",
        "notes": "ORC-3 (Filler Order Number) maps to ServiceRequest.identifier with type='FILL'. This is the accession number for imaging.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("ORC", 5): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.status",
        "fhir_element_type": "code",
        "notes": "ORC-5 (Order Status) maps to ServiceRequest.status. SC->active, IP->active, CM->completed, CA->revoked, HD->on-hold.",
        "conversion_type": "lookup",
        "concept_map": "order-status",
    },
    ("ORC", 9): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.authoredOn",
        "fhir_element_type": "dateTime",
        "notes": "ORC-9 (Date/Time of Transaction) maps to ServiceRequest.authoredOn.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("ORC", 12): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.requester",
        "fhir_element_type": "Reference(Practitioner)",
        "notes": "ORC-12 (Ordering Provider) maps to ServiceRequest.requester. Create a Practitioner resource from XCN data.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBR", 4): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.code",
        "fhir_element_type": "CodeableConcept",
        "notes": "OBR-4 (Universal Service Identifier) maps to ServiceRequest.code. CE.1->coding.code, CE.2->coding.display, CE.3->coding.system.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBR", 7): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.occurrenceDateTime",
        "fhir_element_type": "dateTime",
        "notes": "OBR-7 (Observation Date/Time) maps to when the observation occurred. Also used for DiagnosticReport.effectiveDateTime.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("OBR", 13): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.reasonCode | ServiceRequest.note",
        "fhir_element_type": "CodeableConcept | Annotation",
        "notes": "OBR-13 (Relevant Clinical Information) maps to reasonCode (if coded) or note (if free text). Critical clinical context for imaging.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBR", 16): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.requester",
        "fhir_element_type": "Reference(Practitioner)",
        "notes": "OBR-16 (Ordering Provider) maps to ServiceRequest.requester. Use ORC-12 if both present.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBR", 24): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.category",
        "fhir_element_type": "CodeableConcept",
        "notes": "OBR-24 (Diagnostic Service Section ID) maps to ServiceRequest.category. RAD->imaging, LAB->laboratory, etc.",
        "conversion_type": "lookup",
        "concept_map": "diagnostic-service-section",
    },
    ("OBR", 25): {
        "fhir_resource": "DiagnosticReport",
        "fhir_path": "DiagnosticReport.status",
        "fhir_element_type": "code",
        "notes": "OBR-25 (Result Status) maps to DiagnosticReport.status. O->registered, I->registered, S->registered, A->partial, P->preliminary, F->final, C->amended, X->cancelled, R->registered.",
        "conversion_type": "lookup",
        "concept_map": "result-status",
    },
    ("OBR", 31): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.reasonCode",
        "fhir_element_type": "CodeableConcept",
        "notes": "OBR-31 (Reason for Study) maps to ServiceRequest.reasonCode. May contain ICD codes for medical necessity.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBR", 32): {
        "fhir_resource": "DiagnosticReport",
        "fhir_path": "DiagnosticReport.resultsInterpreter",
        "fhir_element_type": "Reference(Practitioner)",
        "notes": "OBR-32 (Principal Result Interpreter) maps to DiagnosticReport.resultsInterpreter. The reading physician.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBR", 44): {
        "fhir_resource": "ServiceRequest",
        "fhir_path": "ServiceRequest.code",
        "fhir_element_type": "CodeableConcept",
        "notes": "OBR-44 (Procedure Code) provides additional procedure coding (CPT). Added as additional coding on ServiceRequest.code.",
        "conversion_type": "complex",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # OBX -> Observation / DiagnosticReport
    # ---------------------------------------------------------------
    ("OBX", 2): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.value[x]",
        "fhir_element_type": "varies",
        "notes": "OBX-2 (Value Type) determines which Observation.value[x] type to use. NM->valueQuantity, TX/FT/ST->valueString, CE->valueCodeableConcept, TS->valueDateTime. For radiology reports (FT/TX), use DiagnosticReport.presentedForm or Observation.valueString.",
        "conversion_type": "complex",
        "concept_map": "value-type",
    },
    ("OBX", 3): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.code",
        "fhir_element_type": "CodeableConcept",
        "notes": "OBX-3 (Observation Identifier) maps to Observation.code. CE components to CodeableConcept.coding.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBX", 5): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.value[x]",
        "fhir_element_type": "varies",
        "notes": "OBX-5 (Observation Value) maps to the appropriate Observation.value[x] based on OBX-2. For radiology report text, create a DiagnosticReport with presentedForm containing the report text.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("OBX", 6): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.valueQuantity.unit",
        "fhir_element_type": "string",
        "notes": "OBX-6 (Units) maps to the unit component of valueQuantity. Should use UCUM codes in FHIR.",
        "conversion_type": "transform",
        "concept_map": "units-ucum",
    },
    ("OBX", 7): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.referenceRange",
        "fhir_element_type": "Observation.referenceRange",
        "notes": "OBX-7 (References Range) maps to Observation.referenceRange. Parse the text format into low/high components.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("OBX", 8): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.interpretation",
        "fhir_element_type": "CodeableConcept",
        "notes": "OBX-8 (Abnormal Flags) maps to Observation.interpretation. Use system='http://terminology.hl7.org/CodeSystem/v3-ObservationInterpretation'. H->H, L->L, N->N, A->A, etc.",
        "conversion_type": "lookup",
        "concept_map": "abnormal-flags",
    },
    ("OBX", 11): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.status",
        "fhir_element_type": "code",
        "notes": "OBX-11 (Observation Result Status) maps to Observation.status. F->final, P->preliminary, C->amended, D->entered-in-error, R->registered, I->registered, X->cancelled.",
        "conversion_type": "lookup",
        "concept_map": "observation-result-status",
    },
    ("OBX", 14): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.effectiveDateTime",
        "fhir_element_type": "dateTime",
        "notes": "OBX-14 (Date/Time of the Observation) maps to Observation.effectiveDateTime.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("OBX", 16): {
        "fhir_resource": "Observation",
        "fhir_path": "Observation.performer",
        "fhir_element_type": "Reference(Practitioner)",
        "notes": "OBX-16 (Responsible Observer) maps to Observation.performer.",
        "conversion_type": "complex",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # AL1 -> AllergyIntolerance
    # ---------------------------------------------------------------
    ("AL1", 2): {
        "fhir_resource": "AllergyIntolerance",
        "fhir_path": "AllergyIntolerance.category",
        "fhir_element_type": "code",
        "notes": "AL1-2 (Allergen Type Code) maps to AllergyIntolerance.category. DA->medication, FA->food, EA->environment, MA->environment, LA->environment.",
        "conversion_type": "lookup",
        "concept_map": "allergen-type",
    },
    ("AL1", 3): {
        "fhir_resource": "AllergyIntolerance",
        "fhir_path": "AllergyIntolerance.code",
        "fhir_element_type": "CodeableConcept",
        "notes": "AL1-3 (Allergen Code) maps to AllergyIntolerance.code.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("AL1", 4): {
        "fhir_resource": "AllergyIntolerance",
        "fhir_path": "AllergyIntolerance.reaction.severity",
        "fhir_element_type": "code",
        "notes": "AL1-4 (Allergy Severity) maps to reaction.severity. SV->severe, MO->moderate, MI->mild.",
        "conversion_type": "lookup",
        "concept_map": "allergy-severity",
    },
    ("AL1", 5): {
        "fhir_resource": "AllergyIntolerance",
        "fhir_path": "AllergyIntolerance.reaction.manifestation",
        "fhir_element_type": "CodeableConcept",
        "notes": "AL1-5 (Allergy Reaction Code) maps to reaction.manifestation.",
        "conversion_type": "complex",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # DG1 -> Condition
    # ---------------------------------------------------------------
    ("DG1", 3): {
        "fhir_resource": "Condition",
        "fhir_path": "Condition.code",
        "fhir_element_type": "CodeableConcept",
        "notes": "DG1-3 (Diagnosis Code) maps to Condition.code. Use ICD-10 system: 'http://hl7.org/fhir/sid/icd-10-cm'.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("DG1", 5): {
        "fhir_resource": "Condition",
        "fhir_path": "Condition.onsetDateTime",
        "fhir_element_type": "dateTime",
        "notes": "DG1-5 (Diagnosis Date/Time) maps to Condition.onsetDateTime or recordedDate.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("DG1", 6): {
        "fhir_resource": "Condition",
        "fhir_path": "Condition.category",
        "fhir_element_type": "CodeableConcept",
        "notes": "DG1-6 (Diagnosis Type) maps to Condition.category. A->encounter-diagnosis, W->encounter-diagnosis, F->encounter-diagnosis.",
        "conversion_type": "lookup",
        "concept_map": "diagnosis-type",
    },

    # ---------------------------------------------------------------
    # NK1 -> RelatedPerson
    # ---------------------------------------------------------------
    ("NK1", 2): {
        "fhir_resource": "RelatedPerson",
        "fhir_path": "RelatedPerson.name",
        "fhir_element_type": "HumanName",
        "notes": "NK1-2 (NK Name) maps to RelatedPerson.name. Same XPN->HumanName mapping as PID-5.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("NK1", 3): {
        "fhir_resource": "RelatedPerson",
        "fhir_path": "RelatedPerson.relationship",
        "fhir_element_type": "CodeableConcept",
        "notes": "NK1-3 (Relationship) maps to RelatedPerson.relationship. Use system='http://terminology.hl7.org/CodeSystem/v2-0063'.",
        "conversion_type": "lookup",
        "concept_map": "nk1-relationship",
    },
    ("NK1", 4): {
        "fhir_resource": "RelatedPerson",
        "fhir_path": "RelatedPerson.address",
        "fhir_element_type": "Address",
        "notes": "NK1-4 (Address) maps to RelatedPerson.address.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("NK1", 5): {
        "fhir_resource": "RelatedPerson",
        "fhir_path": "RelatedPerson.telecom",
        "fhir_element_type": "ContactPoint",
        "notes": "NK1-5 (Phone Number) maps to RelatedPerson.telecom.",
        "conversion_type": "complex",
        "concept_map": None,
    },

    # ---------------------------------------------------------------
    # IN1 -> Coverage
    # ---------------------------------------------------------------
    ("IN1", 2): {
        "fhir_resource": "Coverage",
        "fhir_path": "Coverage.type",
        "fhir_element_type": "CodeableConcept",
        "notes": "IN1-2 (Insurance Plan ID) maps to Coverage.type.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("IN1", 3): {
        "fhir_resource": "Coverage",
        "fhir_path": "Coverage.payor",
        "fhir_element_type": "Reference(Organization)",
        "notes": "IN1-3 (Insurance Company ID) + IN1-4 (Insurance Company Name) map to an Organization resource referenced by Coverage.payor.",
        "conversion_type": "complex",
        "concept_map": None,
    },
    ("IN1", 12): {
        "fhir_resource": "Coverage",
        "fhir_path": "Coverage.period.start",
        "fhir_element_type": "dateTime",
        "notes": "IN1-12 (Plan Effective Date) maps to Coverage.period.start.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("IN1", 13): {
        "fhir_resource": "Coverage",
        "fhir_path": "Coverage.period.end",
        "fhir_element_type": "dateTime",
        "notes": "IN1-13 (Plan Expiration Date) maps to Coverage.period.end.",
        "conversion_type": "transform",
        "concept_map": None,
    },
    ("IN1", 36): {
        "fhir_resource": "Coverage",
        "fhir_path": "Coverage.identifier",
        "fhir_element_type": "Identifier",
        "notes": "IN1-36 (Policy Number) maps to Coverage.identifier.",
        "conversion_type": "direct",
        "concept_map": None,
    },
}


# ---------------------------------------------------------------
# DICOM to HL7 v2 Field Mapping
# ---------------------------------------------------------------
# Key: (group, element) DICOM tag
# Value: {
#   "hl7_segment": str,
#   "hl7_field": str (segment-position notation),
#   "hl7_component": str | None,
#   "mapping_notes": str,
#   "data_type_conversion": str,
#   "bidirectional": bool
# }

DICOM_TO_HL7_MAP: dict[tuple[int, int], dict] = {
    # Patient Demographics
    (0x0010, 0x0010): {
        "hl7_segment": "PID",
        "hl7_field": "PID-5",
        "hl7_component": None,
        "mapping_notes": "DICOM PN format (Family^Given^Middle^Prefix^Suffix) maps directly to XPN. Note: DICOM uses '=' for component group separator; HL7 does not have component groups.",
        "data_type_conversion": "PN -> XPN",
        "bidirectional": True,
    },
    (0x0010, 0x0020): {
        "hl7_segment": "PID",
        "hl7_field": "PID-3",
        "hl7_component": "PID-3.1",
        "mapping_notes": "DICOM Patient ID maps to PID-3.1 (ID Number). The Assigning Authority (PID-3.4) should come from DICOM (0010,0021) Issuer of Patient ID. Set PID-3.5 to 'MR' for Medical Record Number.",
        "data_type_conversion": "LO -> CX",
        "bidirectional": True,
    },
    (0x0010, 0x0021): {
        "hl7_segment": "PID",
        "hl7_field": "PID-3",
        "hl7_component": "PID-3.4",
        "mapping_notes": "DICOM Issuer of Patient ID maps to the Assigning Authority component of PID-3.",
        "data_type_conversion": "LO -> HD",
        "bidirectional": True,
    },
    (0x0010, 0x0030): {
        "hl7_segment": "PID",
        "hl7_field": "PID-7",
        "hl7_component": None,
        "mapping_notes": "DICOM DA format (YYYYMMDD) maps directly to HL7 TS/DT format. No conversion needed for the date portion.",
        "data_type_conversion": "DA -> TS",
        "bidirectional": True,
    },
    (0x0010, 0x0040): {
        "hl7_segment": "PID",
        "hl7_field": "PID-8",
        "hl7_component": None,
        "mapping_notes": "Direct mapping: M->M, F->F, O->O. DICOM and HL7 use the same values.",
        "data_type_conversion": "CS -> IS",
        "bidirectional": True,
    },
    (0x0010, 0x1030): {
        "hl7_segment": "PID",
        "hl7_field": "OBX (weight observation)",
        "hl7_component": None,
        "mapping_notes": "Patient Weight maps to an OBX observation with LOINC code 29463-7 (Body weight). Value in kg.",
        "data_type_conversion": "DS -> NM",
        "bidirectional": False,
    },
    (0x0010, 0x2110): {
        "hl7_segment": "AL1",
        "hl7_field": "AL1-3",
        "hl7_component": None,
        "mapping_notes": "DICOM Allergies maps to AL1-3 (Allergen Code). Multiple values create multiple AL1 segments.",
        "data_type_conversion": "LO -> CE",
        "bidirectional": True,
    },

    # Study-Level
    (0x0008, 0x0050): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-3 / ORC-3",
        "hl7_component": "OBR-3.1",
        "mapping_notes": "DICOM Accession Number maps to HL7 Filler Order Number. This is THE critical order-linking field. Must match exactly between RIS and PACS.",
        "data_type_conversion": "SH -> EI",
        "bidirectional": True,
    },
    (0x0008, 0x0020): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-7",
        "hl7_component": None,
        "mapping_notes": "DICOM Study Date maps to OBR-7 (Observation Date/Time) date portion. Combine with Study Time (0008,0030) for the full timestamp.",
        "data_type_conversion": "DA -> TS (date portion)",
        "bidirectional": True,
    },
    (0x0008, 0x0030): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-7",
        "hl7_component": "time portion",
        "mapping_notes": "DICOM Study Time maps to the time portion of OBR-7. Combine with Study Date for full timestamp.",
        "data_type_conversion": "TM -> TS (time portion)",
        "bidirectional": True,
    },
    (0x0008, 0x1030): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-4",
        "hl7_component": "OBR-4.2",
        "mapping_notes": "DICOM Study Description maps to the text/description component of OBR-4 (Universal Service Identifier). Note: OBR-4.1 should contain the procedure code, not the description.",
        "data_type_conversion": "LO -> CE (text component)",
        "bidirectional": True,
    },
    (0x0008, 0x0060): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-24",
        "hl7_component": None,
        "mapping_notes": "DICOM Modality maps loosely to OBR-24 (Diagnostic Service Section ID). CT->CT, MR->NMR, US->RUS, etc. Not a 1:1 mapping — OBR-24 uses HL7 Table 0074 values.",
        "data_type_conversion": "CS -> ID (with value mapping)",
        "bidirectional": False,
    },
    (0x0008, 0x0090): {
        "hl7_segment": "PV1 / OBR",
        "hl7_field": "PV1-8 / OBR-16",
        "hl7_component": None,
        "mapping_notes": "DICOM Referring Physician maps to both PV1-8 (Referring Doctor) and OBR-16 (Ordering Provider). PN format to XCN format.",
        "data_type_conversion": "PN -> XCN",
        "bidirectional": True,
    },
    (0x0008, 0x1070): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-34",
        "hl7_component": None,
        "mapping_notes": "DICOM Operators' Name (technologist) maps to OBR-34 (Technician).",
        "data_type_conversion": "PN -> NDL",
        "bidirectional": True,
    },

    # Visit/Encounter
    (0x0038, 0x0010): {
        "hl7_segment": "PV1",
        "hl7_field": "PV1-19",
        "hl7_component": "PV1-19.1",
        "mapping_notes": "DICOM Admission ID maps to PV1-19 (Visit Number). Links imaging to the hospital encounter. Also maps to PID-18 (Account Number) in some implementations.",
        "data_type_conversion": "LO -> CX",
        "bidirectional": True,
    },

    # Procedure/Worklist
    (0x0040, 0x0001): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-21 (custom) / MWL",
        "hl7_component": None,
        "mapping_notes": "DICOM Scheduled Station AE Title is used in MWL queries. No direct HL7 v2 standard mapping, but often placed in OBR-20 or OBR-21 as a local convention.",
        "data_type_conversion": "AE -> ST",
        "bidirectional": False,
    },
    (0x0040, 0x0007): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-4",
        "hl7_component": "OBR-4.2",
        "mapping_notes": "DICOM Scheduled Procedure Step Description maps to OBR-4 description component. Same mapping as Study Description for the scheduled context.",
        "data_type_conversion": "LO -> CE (text component)",
        "bidirectional": True,
    },
    (0x0040, 0x0009): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-20",
        "hl7_component": None,
        "mapping_notes": "DICOM Scheduled Procedure Step ID maps to OBR-20 (Filler Field 1). Implementation-specific; no standard mapping.",
        "data_type_conversion": "SH -> ST",
        "bidirectional": True,
    },
    (0x0040, 0x1001): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-19 / ORC-2",
        "hl7_component": None,
        "mapping_notes": "DICOM Requested Procedure ID maps to OBR-19 (Placer Field 2) or maps to ORC-2 (Placer Order Number) in some implementations.",
        "data_type_conversion": "SH -> ST / EI",
        "bidirectional": True,
    },
    (0x0032, 0x1060): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-4",
        "hl7_component": "OBR-4.2",
        "mapping_notes": "DICOM Requested Procedure Description maps to OBR-4 text component.",
        "data_type_conversion": "LO -> CE",
        "bidirectional": True,
    },
    (0x0032, 0x1032): {
        "hl7_segment": "OBR",
        "hl7_field": "OBR-16",
        "hl7_component": None,
        "mapping_notes": "DICOM Requesting Physician maps to OBR-16 (Ordering Provider).",
        "data_type_conversion": "PN -> XCN",
        "bidirectional": True,
    },

    # Instance/Image Level
    (0x0020, 0x000D): {
        "hl7_segment": "ZDS (custom) / OBX",
        "hl7_field": "ZDS-1 / OBX-5",
        "hl7_component": None,
        "mapping_notes": "DICOM Study Instance UID has no standard HL7 v2 field. Commonly placed in a ZDS (custom Z-segment) or in an OBX segment with a local observation identifier. IHE RAD-28 uses ZDS-1.",
        "data_type_conversion": "UI -> RP/ST",
        "bidirectional": True,
    },
    (0x0008, 0x0016): {
        "hl7_segment": "OBX",
        "hl7_field": "OBX-5 (embedded)",
        "hl7_component": None,
        "mapping_notes": "DICOM SOP Class UID may be embedded in OBX observation data when transmitting DICOM metadata via HL7. No standard field mapping.",
        "data_type_conversion": "UI -> ST",
        "bidirectional": False,
    },
}


# ---------------------------------------------------------------
# Integration Patterns
# ---------------------------------------------------------------
INTEGRATION_PATTERNS: dict[str, dict] = {
    "adt_feed": {
        "name": "ADT Feed (Patient Demographics)",
        "description": "Real-time patient admission/discharge/transfer events from HIS/EHR to downstream systems.",
        "message_flow": [
            "HIS/EHR -> Interface Engine -> PACS",
            "HIS/EHR -> Interface Engine -> RIS",
            "HIS/EHR -> Interface Engine -> Departmental Systems",
        ],
        "trigger_events": ["A01 (Admit)", "A02 (Transfer)", "A03 (Discharge)", "A04 (Register)", "A08 (Update)", "A34/A40 (Merge)"],
        "expected_segments": ["MSH", "EVN", "PID", "PV1"],
        "common_pitfalls": [
            "Patient ID format mismatch between HIS and PACS (leading zeros, padding)",
            "Name format differences (PN vs XPN, component ordering)",
            "Merge events (A34/A40) not properly handled — leads to duplicate patients in PACS",
            "A08 (Update) flood — some ADT systems send A08 for every minor change, overwhelming downstream systems",
            "Character set issues with non-ASCII patient names",
            "Missing or incorrect PV1-2 (Patient Class) causing wrong encounter type",
        ],
        "best_practices": [
            "Always process merge events (A34/A40) — duplicate patients cause clinical risk",
            "Implement patient matching logic as fallback when MRN doesn't match",
            "Filter high-volume A08 events to only forward clinically relevant changes",
            "Validate patient demographics before updating PACS master patient index",
            "Log all ADT events with timestamps for audit trail",
        ],
    },
    "order_to_result": {
        "name": "Order to Result (ORM/ORU) Workflow",
        "description": "Complete order lifecycle from order placement through result delivery.",
        "message_flow": [
            "CPOE/EHR -> ORM^O01 (NW) -> Interface Engine -> RIS (Order Received)",
            "RIS -> ORM^O01 (SC) -> Interface Engine -> CPOE/EHR (Status Update: Scheduled)",
            "Modality -> MWL Query -> RIS (Worklist retrieval)",
            "Modality -> DICOM Store -> PACS (Images stored)",
            "Modality -> MPPS -> RIS (Exam complete notification)",
            "RIS -> ORM^O01 (SC) -> Interface Engine -> CPOE/EHR (Status: In Progress/Complete)",
            "Radiologist dictates -> RIS creates report",
            "RIS -> ORU^R01 (P) -> Interface Engine -> CPOE/EHR (Preliminary Report)",
            "RIS -> ORU^R01 (F) -> Interface Engine -> CPOE/EHR (Final Report)",
        ],
        "trigger_events": [
            "ORM^O01 with ORC-1=NW (New Order)",
            "ORM^O01 with ORC-1=SC (Status Changed)",
            "ORM^O01 with ORC-1=CA (Cancel)",
            "ORU^R01 with OBR-25=P (Preliminary Result)",
            "ORU^R01 with OBR-25=F (Final Result)",
            "ORU^R01 with OBR-25=C (Corrected Result)",
        ],
        "expected_segments": ["MSH", "PID", "PV1", "ORC", "OBR", "OBX (for results)"],
        "common_pitfalls": [
            "Accession number mismatch between ORC-3/OBR-3 and DICOM (0008,0050)",
            "Order status not properly tracked through all states",
            "Preliminary results treated as final by receiving system",
            "Corrected results (OBR-25=C) not replacing the original in the EHR",
            "Missing clinical history in OBR-13 — radiologists need this context",
            "Ordering provider (ORC-12/OBR-16) format inconsistencies",
            "Cancel orders not properly removing from modality worklist",
        ],
        "best_practices": [
            "Use Accession Number as the single linking key between RIS and PACS",
            "Implement bidirectional order status tracking",
            "Include clinical indication (OBR-13) in all imaging orders",
            "Handle preliminary (P), final (F), and corrected (C) result statuses",
            "Send acknowledgments (ACK) for every received message",
            "Implement order reconciliation for unmatched studies",
        ],
    },
    "radiology_workflow": {
        "name": "Radiology Workflow (IHE Scheduled Workflow Profile)",
        "description": "IHE Scheduled Workflow (SWF) integration profile for radiology departments.",
        "message_flow": [
            "1. Order Placer (EHR) -> ORM -> Order Filler (RIS): Order placed",
            "2. RIS schedules procedure on modality worklist",
            "3. Modality -> MWL C-FIND -> RIS: Query worklist for patient",
            "4. Technologist selects patient from worklist, begins exam",
            "5. Modality -> MPPS N-CREATE -> RIS: Procedure started (In Progress)",
            "6. Modality acquires images",
            "7. Modality -> DICOM C-STORE -> PACS: Images stored",
            "8. Modality -> MPPS N-SET -> RIS: Procedure completed",
            "9. RIS updates order status -> ORM (SC) -> EHR",
            "10. PACS -> Storage Commitment -> Modality: Images safely stored",
            "11. Radiologist reads study on PACS viewer",
            "12. Radiologist dictates report in RIS",
            "13. RIS -> ORU (P) -> EHR: Preliminary report",
            "14. Report finalized/signed",
            "15. RIS -> ORU (F) -> EHR: Final report",
        ],
        "trigger_events": ["ORM^O01", "ORU^R01", "MWL C-FIND", "MPPS N-CREATE/N-SET", "DICOM C-STORE", "Storage Commitment"],
        "expected_segments": ["MSH", "PID", "PV1", "ORC", "OBR", "OBX"],
        "common_pitfalls": [
            "MWL not returning correct worklist entries (AE Title mismatch, date range too narrow)",
            "Patient/study mismatch when tech selects wrong worklist entry",
            "MPPS not implemented — RIS doesn't know when exam is done",
            "Images stored on PACS before RIS has the order (unmatched studies)",
            "Prior study pre-fetch failing due to incorrect patient matching",
            "Hanging protocol failures due to inconsistent Series Description values",
            "Storage Commitment not implemented — modality can't safely delete local copies",
        ],
        "best_practices": [
            "Implement all three IHE SWF actors: Order Placer, Order Filler, Image Manager/Archive",
            "Use MPPS for reliable exam completion tracking",
            "Implement study reconciliation for unmatched studies",
            "Configure MWL to return only today's scheduled procedures plus recent unmatched",
            "Use Accession Number as the universal linking key across all systems",
            "Test modality worklist with each scanner model before go-live",
        ],
    },
    "lab_interface": {
        "name": "Laboratory Interface (Order/Result)",
        "description": "Laboratory order and result integration between EHR and LIS.",
        "message_flow": [
            "EHR -> ORM^O01 (NW) -> Interface Engine -> LIS (Order placed)",
            "LIS -> ORM^O01 (OK) -> Interface Engine -> EHR (Order accepted)",
            "Specimen collected, tested",
            "LIS -> ORU^R01 (P) -> Interface Engine -> EHR (Preliminary result)",
            "LIS -> ORU^R01 (F) -> Interface Engine -> EHR (Final result)",
        ],
        "trigger_events": ["ORM^O01 (NW/CA)", "ORU^R01 (P/F/C)"],
        "expected_segments": ["MSH", "PID", "PV1", "ORC", "OBR", "OBX", "SPM (v2.5+)"],
        "common_pitfalls": [
            "Test code mapping between EHR and LIS (different code systems)",
            "Unit of measure differences",
            "Reference range format inconsistencies",
            "Abnormal flag interpretation differences",
            "Microbiology results with complex hierarchical OBX structure",
            "Add-on orders not properly linked to original specimen",
        ],
        "best_practices": [
            "Maintain a master test code crosswalk table",
            "Use LOINC codes when possible for interoperability",
            "Implement specimen tracking with SPM segment (v2.5+)",
            "Handle all result statuses (P, F, C, X)",
            "Parse multi-line OBX results correctly for micro cultures",
        ],
    },
    "report_distribution": {
        "name": "Report Distribution (MDM/ORU)",
        "description": "Distribution of clinical documents and reports to EMR/EHR systems.",
        "message_flow": [
            "Dictation System -> Transcription -> RIS",
            "RIS -> ORU^R01 or MDM^T02 -> Interface Engine -> EHR (Report distribution)",
            "EHR stores report and links to order/encounter",
            "RIS -> MDM^T02 -> Interface Engine -> Health Information Exchange (external distribution)",
        ],
        "trigger_events": ["ORU^R01 (P/F/C)", "MDM^T01 (notification only)", "MDM^T02 (with content)", "MDM^T09 (addendum)"],
        "expected_segments": ["MSH", "PID", "PV1", "ORC", "OBR", "OBX (report text)", "TXA (for MDM)"],
        "common_pitfalls": [
            "Report formatting lost in translation (FT escape sequences not rendered)",
            "Preliminary reports displayed as final",
            "Corrected reports not replacing original in EHR",
            "Addenda not properly linked to original report",
            "PDF reports (OBX-2=ED) not handled by receiving system",
            "Report delivered before order exists in EHR (timing issue)",
            "Critical/stat results not triggering appropriate alerts",
        ],
        "best_practices": [
            "Use consistent report formatting (FT for formatted text, TX for plain text)",
            "Include both impression and full findings in structured OBX segments",
            "Send preliminary notifications to enable timely clinical review",
            "Implement critical result tracking with read-back acknowledgment",
            "Support both text-based and PDF report formats",
            "Include the reading physician in OBR-32 for all reports",
        ],
    },
    "patient_merge": {
        "name": "Patient Merge/Link (MPI Management)",
        "description": "Handling duplicate patient records through merge and link operations.",
        "message_flow": [
            "MPI System identifies duplicate records",
            "MPI -> ADT^A40 (or A34/A18) -> Interface Engine -> All downstream systems",
            "Each downstream system merges data from the incorrect MRN to the correct MRN",
            "PACS reassigns all studies from old MRN to surviving MRN",
            "RIS updates orders, reports, and history",
        ],
        "trigger_events": ["A34 (Merge Patient ID Only)", "A40 (Merge Patient Identifier List)", "A18 (Merge Patient Information)"],
        "expected_segments": ["MSH", "EVN", "PID (surviving)", "MRG (merged-away)", "PV1"],
        "common_pitfalls": [
            "PACS doesn't properly merge — images orphaned under old MRN",
            "Merge processed out of order (demographics update arrives after merge)",
            "Circular merge (A merged into B, then B merged into A)",
            "Merge not propagated to all downstream systems",
            "Report links broken after merge",
            "Prior studies not found under new MRN after merge",
        ],
        "best_practices": [
            "Treat merge events as highest priority — process immediately",
            "Log all merge events for audit trail",
            "Verify merge completion in all downstream systems",
            "Implement merge validation (prevent merging different actual patients)",
            "Support unmerge capability for incorrect merges",
            "Test merge scenarios thoroughly before go-live, especially with PACS",
        ],
    },
    "charge_posting": {
        "name": "Charge Posting (DFT/BAR)",
        "description": "Financial transaction posting for imaging procedures.",
        "message_flow": [
            "RIS -> DFT^P03 -> Interface Engine -> Billing System (charge posted)",
            "Alternatively: RIS -> BAR^P01 -> Interface Engine -> Billing System",
            "Billing System processes charge and submits claim",
        ],
        "trigger_events": ["DFT^P03", "BAR^P01"],
        "expected_segments": ["MSH", "EVN", "PID", "PV1", "FT1", "DG1"],
        "common_pitfalls": [
            "CPT code mapping errors between RIS and billing system",
            "Missing or incorrect diagnosis codes (medical necessity denial)",
            "Duplicate charges for repeated/corrected exams",
            "Charge posted before insurance verification",
            "Professional vs. technical component not properly separated",
            "Modifier codes missing or incorrect",
        ],
        "best_practices": [
            "Validate CPT codes against payer rules before posting",
            "Include ICD-10 diagnosis codes (DG1) with every charge",
            "Implement duplicate charge detection",
            "Support charge correction/reversal workflow",
            "Track charge status for reconciliation",
        ],
    },
}
