"""
Comprehensive HL7 v2.x segment definitions.

Contains accurate field definitions for the most commonly used HL7 v2.x
segments, including field positions, data types, optionality, table references,
and practical integration notes.

Reference: HL7 v2.5.1 Standard (with notes for v2.3, v2.4, v2.7 differences)
"""

# Each segment: segment_id -> {
#   "name": str,
#   "description": str,
#   "fields": [{
#       "position": int,
#       "name": str,
#       "data_type": str,
#       "max_length": int,
#       "required": str (R=Required, RE=Required but may be Empty, O=Optional, C=Conditional, B=Backward compat),
#       "repeating": bool,
#       "table": str | None,
#       "description": str
#   }],
#   "notes": str
# }

HL7_SEGMENTS: dict[str, dict] = {
    "MSH": {
        "name": "Message Header",
        "description": "Defines the intent, source, destination, and some specifics of the syntax of a message.",
        "fields": [
            {"position": 1, "name": "Field Separator", "data_type": "ST", "max_length": 1, "required": "R", "repeating": False, "table": None, "description": "Separates fields. Always '|'."},
            {"position": 2, "name": "Encoding Characters", "data_type": "ST", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Component separator, repetition separator, escape character, subcomponent separator. Usually '^~\\&'."},
            {"position": 3, "name": "Sending Application", "data_type": "HD", "max_length": 227, "required": "O", "repeating": False, "table": "0361", "description": "Identifies the sending application (e.g., 'RIS', 'PACS', 'ADT')."},
            {"position": 4, "name": "Sending Facility", "data_type": "HD", "max_length": 227, "required": "O", "repeating": False, "table": "0362", "description": "Identifies the sending facility (e.g., 'HOSPITAL_A', site OID)."},
            {"position": 5, "name": "Receiving Application", "data_type": "HD", "max_length": 227, "required": "O", "repeating": False, "table": "0361", "description": "Identifies the receiving application."},
            {"position": 6, "name": "Receiving Facility", "data_type": "HD", "max_length": 227, "required": "O", "repeating": False, "table": "0362", "description": "Identifies the receiving facility."},
            {"position": 7, "name": "Date/Time of Message", "data_type": "TS", "max_length": 26, "required": "R", "repeating": False, "table": None, "description": "Date/time the message was created. Format: YYYYMMDDHHMMSS[.S[S[S[S]]]][+/-ZZZZ]."},
            {"position": 8, "name": "Security", "data_type": "ST", "max_length": 40, "required": "O", "repeating": False, "table": None, "description": "Security/access control. Rarely used in practice."},
            {"position": 9, "name": "Message Type", "data_type": "MSG", "max_length": 15, "required": "R", "repeating": False, "table": "0076", "description": "Message type and trigger event (e.g., ADT^A01, ORM^O01, ORU^R01)."},
            {"position": 10, "name": "Message Control ID", "data_type": "ST", "max_length": 199, "required": "R", "repeating": False, "table": None, "description": "Unique ID for this message. Used in acknowledgments (MSA-2). Must be unique within sending application."},
            {"position": 11, "name": "Processing ID", "data_type": "PT", "max_length": 3, "required": "R", "repeating": False, "table": "0103", "description": "P=Production, D=Debugging, T=Training. Critical: never send test messages with 'P'."},
            {"position": 12, "name": "Version ID", "data_type": "VID", "max_length": 60, "required": "R", "repeating": False, "table": "0104", "description": "HL7 version (e.g., '2.3', '2.3.1', '2.5', '2.5.1')."},
            {"position": 13, "name": "Sequence Number", "data_type": "NM", "max_length": 15, "required": "O", "repeating": False, "table": None, "description": "Sequence number for message ordering. Rarely used."},
            {"position": 14, "name": "Continuation Pointer", "data_type": "ST", "max_length": 180, "required": "O", "repeating": False, "table": None, "description": "Used for continuation of long messages."},
            {"position": 15, "name": "Accept Acknowledgment Type", "data_type": "ID", "max_length": 2, "required": "O", "repeating": False, "table": "0155", "description": "AL=Always, NE=Never, ER=Error/reject only, SU=Successful only."},
            {"position": 16, "name": "Application Acknowledgment Type", "data_type": "ID", "max_length": 2, "required": "O", "repeating": False, "table": "0155", "description": "Same values as MSH-15."},
            {"position": 17, "name": "Country Code", "data_type": "ID", "max_length": 3, "required": "O", "repeating": False, "table": "0399", "description": "ISO 3166 country code (e.g., 'USA', 'GBR')."},
            {"position": 18, "name": "Character Set", "data_type": "ID", "max_length": 16, "required": "O", "repeating": True, "table": "0211", "description": "Character set for the message (e.g., 'ASCII', 'UNICODE UTF-8')."},
            {"position": 19, "name": "Principal Language of Message", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Primary language of the message content."},
            {"position": 20, "name": "Alternate Character Set Handling Scheme", "data_type": "ID", "max_length": 20, "required": "O", "repeating": False, "table": "0356", "description": "How alternate character sets are used."},
            {"position": 21, "name": "Message Profile Identifier", "data_type": "EI", "max_length": 427, "required": "O", "repeating": True, "table": None, "description": "Identifies the message profile (conformance statement). Added in v2.5."},
        ],
        "notes": "Always the first segment in any HL7 message. MSH-1 and MSH-2 are special: MSH-1 IS the field separator itself (counted but not delimited). The pipe character between 'MSH' and '^~\\&' is MSH-1.",
    },

    "EVN": {
        "name": "Event Type",
        "description": "Communicates trigger event information to the receiving application.",
        "fields": [
            {"position": 1, "name": "Event Type Code", "data_type": "ID", "max_length": 3, "required": "B", "repeating": False, "table": "0003", "description": "Event type (A01, A02, etc.). Backward compatible; use MSH-9 trigger event instead."},
            {"position": 2, "name": "Recorded Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time the event was recorded in the source system."},
            {"position": 3, "name": "Date/Time Planned Event", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time the event is planned to occur."},
            {"position": 4, "name": "Event Reason Code", "data_type": "IS", "max_length": 3, "required": "O", "repeating": False, "table": "0062", "description": "Reason for the event (e.g., patient request, physician order)."},
            {"position": 5, "name": "Operator ID", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": "0188", "description": "ID of the person who triggered the event."},
            {"position": 6, "name": "Event Occurred", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time the event actually occurred."},
            {"position": 7, "name": "Event Facility", "data_type": "HD", "max_length": 241, "required": "O", "repeating": False, "table": None, "description": "Facility where the event occurred."},
        ],
        "notes": "Required in ADT messages. EVN-1 is retained for backward compatibility; the trigger event in MSH-9 is authoritative.",
    },

    "PID": {
        "name": "Patient Identification",
        "description": "Contains patient identification and demographic information.",
        "fields": [
            {"position": 1, "name": "Set ID - PID", "data_type": "SI", "max_length": 4, "required": "O", "repeating": False, "table": None, "description": "Sequence number for multiple PID segments. Usually '1'."},
            {"position": 2, "name": "Patient ID (External)", "data_type": "CX", "max_length": 20, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use PID-3. External patient ID."},
            {"position": 3, "name": "Patient Identifier List", "data_type": "CX", "max_length": 250, "required": "R", "repeating": True, "table": None, "description": "List of patient identifiers (MRN, SSN, etc.). Components: ID^Check Digit^Check Digit Scheme^Assigning Authority^ID Type Code. ID Type: MR=MRN, SS=SSN, DL=Driver's License."},
            {"position": 4, "name": "Alternate Patient ID", "data_type": "CX", "max_length": 20, "required": "B", "repeating": True, "table": None, "description": "DEPRECATED. Use PID-3 with repeating identifiers."},
            {"position": 5, "name": "Patient Name", "data_type": "XPN", "max_length": 250, "required": "R", "repeating": True, "table": None, "description": "Patient's legal name. Format: FamilyName^GivenName^MiddleName^Suffix^Prefix^Degree. First repetition is legal name."},
            {"position": 6, "name": "Mother's Maiden Name", "data_type": "XPN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Mother's maiden name. Used for patient matching in some systems."},
            {"position": 7, "name": "Date/Time of Birth", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Patient's date of birth. Format: YYYYMMDD[HHMM]."},
            {"position": 8, "name": "Administrative Sex", "data_type": "IS", "max_length": 1, "required": "O", "repeating": False, "table": "0001", "description": "Patient's sex. F=Female, M=Male, O=Other, U=Unknown, A=Ambiguous, N=Not applicable."},
            {"position": 9, "name": "Patient Alias", "data_type": "XPN", "max_length": 250, "required": "B", "repeating": True, "table": None, "description": "DEPRECATED in v2.4+. Use PID-5 with repeating names and name type code."},
            {"position": 10, "name": "Race", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": "0005", "description": "Patient's race."},
            {"position": 11, "name": "Patient Address", "data_type": "XAD", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Patient's mailing address. Components: Street^Other^City^State^Zip^Country^Type."},
            {"position": 12, "name": "County Code", "data_type": "IS", "max_length": 4, "required": "B", "repeating": False, "table": "0289", "description": "DEPRECATED. Use PID-11 component 9."},
            {"position": 13, "name": "Phone Number - Home", "data_type": "XTN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Patient's home phone. Deprecated in v2.7+; use PID-40."},
            {"position": 14, "name": "Phone Number - Business", "data_type": "XTN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Patient's business phone. Deprecated in v2.7+; use PID-40."},
            {"position": 15, "name": "Primary Language", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0296", "description": "Patient's primary language."},
            {"position": 16, "name": "Marital Status", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0002", "description": "Patient's marital status. S=Single, M=Married, D=Divorced, W=Widowed, etc."},
            {"position": 17, "name": "Religion", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0006", "description": "Patient's religion."},
            {"position": 18, "name": "Patient Account Number", "data_type": "CX", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Patient's account/visit number for billing. Maps to DICOM (0038,0010) Admission ID."},
            {"position": 19, "name": "SSN Number - Patient", "data_type": "ST", "max_length": 16, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use PID-3 with identifier type code 'SS'. Social Security Number."},
            {"position": 20, "name": "Driver's License Number", "data_type": "DLN", "max_length": 25, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use PID-3."},
            {"position": 21, "name": "Mother's Identifier", "data_type": "CX", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Identifier of patient's mother. Used in newborn linkage."},
            {"position": 22, "name": "Ethnic Group", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": "0189", "description": "Patient's ethnic group."},
            {"position": 23, "name": "Birth Place", "data_type": "ST", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Patient's birth place."},
            {"position": 24, "name": "Multiple Birth Indicator", "data_type": "ID", "max_length": 1, "required": "O", "repeating": False, "table": "0136", "description": "Y/N indicator for multiple birth."},
            {"position": 25, "name": "Birth Order", "data_type": "NM", "max_length": 2, "required": "O", "repeating": False, "table": None, "description": "Birth order for multiple births."},
            {"position": 26, "name": "Citizenship", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": "0171", "description": "Patient's citizenship."},
            {"position": 27, "name": "Veterans Military Status", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0172", "description": "Patient's military/veteran status."},
            {"position": 28, "name": "Nationality", "data_type": "CE", "max_length": 250, "required": "B", "repeating": False, "table": "0212", "description": "DEPRECATED in v2.4+."},
            {"position": 29, "name": "Patient Death Date and Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time of patient death."},
            {"position": 30, "name": "Patient Death Indicator", "data_type": "ID", "max_length": 1, "required": "O", "repeating": False, "table": "0136", "description": "Y=Patient is deceased."},
        ],
        "notes": "PID-3 is THE critical field for patient matching. In multi-facility environments, the Assigning Authority component (PID-3.4) distinguishes between different MRN domains. PID-18 (Account Number) maps to the visit/encounter. All PID fields containing patient data are PHI under HIPAA.",
    },

    "PV1": {
        "name": "Patient Visit",
        "description": "Contains information about the patient visit (encounter).",
        "fields": [
            {"position": 1, "name": "Set ID - PV1", "data_type": "SI", "max_length": 4, "required": "O", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "Patient Class", "data_type": "IS", "max_length": 1, "required": "R", "repeating": False, "table": "0004", "description": "E=Emergency, I=Inpatient, O=Outpatient, P=Preadmit, R=Recurring, B=Obstetrics, C=Commercial Account, N=Not Applicable, U=Unknown."},
            {"position": 3, "name": "Assigned Patient Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Patient location. Components: Point of Care^Room^Bed^Facility^Location Status^Person Location Type^Building^Floor."},
            {"position": 4, "name": "Admission Type", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0007", "description": "A=Accident, E=Emergency, L=Labor and Delivery, R=Routine, N=Newborn, U=Urgent."},
            {"position": 5, "name": "Preadmit Number", "data_type": "CX", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Number assigned during preadmission."},
            {"position": 6, "name": "Prior Patient Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Previous patient location (for transfers)."},
            {"position": 7, "name": "Attending Doctor", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": "0010", "description": "Attending physician. Format: ID^FamilyName^GivenName^Middle^Suffix^Prefix^Degree^SourceTable^AssigningAuthority."},
            {"position": 8, "name": "Referring Doctor", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": "0010", "description": "Referring physician. Maps to DICOM (0008,0090)."},
            {"position": 9, "name": "Consulting Doctor", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": "0010", "description": "Consulting physician(s)."},
            {"position": 10, "name": "Hospital Service", "data_type": "IS", "max_length": 3, "required": "O", "repeating": False, "table": "0069", "description": "Service or specialty (e.g., MED, SUR, RAD, CAR)."},
            {"position": 11, "name": "Temporary Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Temporary patient location."},
            {"position": 12, "name": "Preadmit Test Indicator", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0087", "description": "Whether preadmission testing is required."},
            {"position": 13, "name": "Re-admission Indicator", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0092", "description": "R=Re-admission."},
            {"position": 14, "name": "Admit Source", "data_type": "IS", "max_length": 6, "required": "O", "repeating": False, "table": "0023", "description": "Source of admission (e.g., physician referral, transfer, ER)."},
            {"position": 15, "name": "Ambulatory Status", "data_type": "IS", "max_length": 2, "required": "O", "repeating": True, "table": "0009", "description": "Patient's ambulatory status."},
            {"position": 16, "name": "VIP Indicator", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0099", "description": "VIP status for special handling."},
            {"position": 17, "name": "Admitting Doctor", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": "0010", "description": "Physician who admitted the patient."},
            {"position": 18, "name": "Patient Type", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0018", "description": "Patient type classification."},
            {"position": 19, "name": "Visit Number", "data_type": "CX", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Unique visit/encounter identifier. Maps to DICOM (0038,0010) Admission ID. Critical for linking imaging to encounters."},
            {"position": 20, "name": "Financial Class", "data_type": "FC", "max_length": 50, "required": "O", "repeating": True, "table": "0064", "description": "Financial class (insurance category)."},
            {"position": 21, "name": "Charge Price Indicator", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0032", "description": "Charge price category."},
            {"position": 22, "name": "Courtesy Code", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0045", "description": "Courtesy given to patient."},
            {"position": 23, "name": "Credit Rating", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0046", "description": "Patient's credit rating."},
            {"position": 24, "name": "Contract Code", "data_type": "IS", "max_length": 2, "required": "O", "repeating": True, "table": "0044", "description": "Type of contract."},
            {"position": 25, "name": "Contract Effective Date", "data_type": "DT", "max_length": 8, "required": "O", "repeating": True, "table": None, "description": "Contract start date."},
            {"position": 26, "name": "Contract Amount", "data_type": "NM", "max_length": 12, "required": "O", "repeating": True, "table": None, "description": "Contract amount."},
            {"position": 27, "name": "Contract Period", "data_type": "NM", "max_length": 3, "required": "O", "repeating": True, "table": None, "description": "Contract period in days."},
            {"position": 28, "name": "Interest Code", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0073", "description": "Interest type."},
            {"position": 29, "name": "Transfer to Bad Debt Code", "data_type": "IS", "max_length": 4, "required": "O", "repeating": False, "table": "0110", "description": "Bad debt transfer code."},
            {"position": 30, "name": "Transfer to Bad Debt Date", "data_type": "DT", "max_length": 8, "required": "O", "repeating": False, "table": None, "description": "Date transferred to bad debt."},
            {"position": 31, "name": "Bad Debt Agency Code", "data_type": "IS", "max_length": 10, "required": "O", "repeating": False, "table": "0021", "description": "Bad debt collection agency."},
            {"position": 32, "name": "Bad Debt Transfer Amount", "data_type": "NM", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Amount transferred to bad debt."},
            {"position": 33, "name": "Bad Debt Recovery Amount", "data_type": "NM", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Amount recovered from bad debt."},
            {"position": 34, "name": "Delete Account Indicator", "data_type": "IS", "max_length": 1, "required": "O", "repeating": False, "table": "0111", "description": "Delete account flag."},
            {"position": 35, "name": "Delete Account Date", "data_type": "DT", "max_length": 8, "required": "O", "repeating": False, "table": None, "description": "Date account was deleted."},
            {"position": 36, "name": "Discharge Disposition", "data_type": "IS", "max_length": 3, "required": "O", "repeating": False, "table": "0112", "description": "Disposition at discharge (home, expired, AMA, etc.)."},
            {"position": 37, "name": "Discharged to Location", "data_type": "DLD", "max_length": 47, "required": "O", "repeating": False, "table": "0113", "description": "Location discharged to (SNF, home health, etc.)."},
            {"position": 38, "name": "Diet Type", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0114", "description": "Patient's diet type."},
            {"position": 39, "name": "Servicing Facility", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0115", "description": "Facility providing patient services."},
            {"position": 40, "name": "Bed Status", "data_type": "IS", "max_length": 1, "required": "B", "repeating": False, "table": "0116", "description": "DEPRECATED. Bed status."},
            {"position": 41, "name": "Account Status", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0117", "description": "Account status."},
            {"position": 42, "name": "Pending Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Pending patient location."},
            {"position": 43, "name": "Prior Temporary Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Previous temporary location."},
            {"position": 44, "name": "Admit Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time of admission."},
            {"position": 45, "name": "Discharge Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": True, "table": None, "description": "Date/time of discharge."},
            {"position": 46, "name": "Current Patient Balance", "data_type": "NM", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Current patient balance."},
            {"position": 47, "name": "Total Charges", "data_type": "NM", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Total charges for the visit."},
            {"position": 48, "name": "Total Adjustments", "data_type": "NM", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Total adjustments."},
            {"position": 49, "name": "Total Payments", "data_type": "NM", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Total payments received."},
            {"position": 50, "name": "Alternate Visit ID", "data_type": "CX", "max_length": 250, "required": "O", "repeating": False, "table": "0203", "description": "Alternate visit identifier."},
            {"position": 51, "name": "Visit Indicator", "data_type": "IS", "max_length": 1, "required": "O", "repeating": False, "table": "0326", "description": "V=Visit, A=Account. Distinguishes visit-level from account-level."},
            {"position": 52, "name": "Other Healthcare Provider", "data_type": "XCN", "max_length": 250, "required": "B", "repeating": True, "table": "0010", "description": "DEPRECATED in v2.4+. Other healthcare provider."},
        ],
        "notes": "PV1-2 (Patient Class) is required and drives many downstream systems. PV1-7 (Attending), PV1-8 (Referring), and PV1-19 (Visit Number) are the most commonly used fields for imaging interfaces. For outpatient imaging, PV1-2 is typically 'O'. PV1-3 location affects where reports are delivered.",
    },

    "PV2": {
        "name": "Patient Visit - Additional Information",
        "description": "Contains additional visit-level information.",
        "fields": [
            {"position": 1, "name": "Prior Pending Location", "data_type": "PL", "max_length": 80, "required": "C", "repeating": False, "table": None, "description": "Previous pending location."},
            {"position": 2, "name": "Accommodation Code", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0129", "description": "Accommodation type (private, semi-private)."},
            {"position": 3, "name": "Admit Reason", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Reason for admission."},
            {"position": 4, "name": "Transfer Reason", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Reason for transfer."},
            {"position": 5, "name": "Patient Valuables", "data_type": "ST", "max_length": 25, "required": "O", "repeating": True, "table": None, "description": "Description of patient valuables."},
            {"position": 6, "name": "Patient Valuables Location", "data_type": "ST", "max_length": 25, "required": "O", "repeating": False, "table": None, "description": "Where valuables are stored."},
            {"position": 7, "name": "Visit User Code", "data_type": "IS", "max_length": 2, "required": "O", "repeating": True, "table": "0130", "description": "User-defined visit category."},
            {"position": 8, "name": "Expected Admit Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Expected admission date/time."},
            {"position": 9, "name": "Expected Discharge Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Expected discharge date/time."},
        ],
        "notes": "Optional extension of PV1. Less commonly used in imaging interfaces but may contain clinical context useful for radiologists.",
    },

    "ORC": {
        "name": "Common Order",
        "description": "Contains information common to all orders.",
        "fields": [
            {"position": 1, "name": "Order Control", "data_type": "ID", "max_length": 2, "required": "R", "repeating": False, "table": "0119", "description": "NW=New Order, CA=Cancel, DC=Discontinue, SC=Status Changed, XO=Change Order, RE=Observations/Performed, HD=Hold, RL=Release, PA=Parent Order, CH=Child Order."},
            {"position": 2, "name": "Placer Order Number", "data_type": "EI", "max_length": 427, "required": "C", "repeating": False, "table": None, "description": "Order number from the ordering system (e.g., CPOE order number). Required on new orders."},
            {"position": 3, "name": "Filler Order Number", "data_type": "EI", "max_length": 427, "required": "C", "repeating": False, "table": None, "description": "Order number from the filling system (e.g., RIS accession number). Required on results. Maps to DICOM Accession Number."},
            {"position": 4, "name": "Placer Group Number", "data_type": "EI", "max_length": 427, "required": "O", "repeating": False, "table": None, "description": "Groups related orders from the same placer."},
            {"position": 5, "name": "Order Status", "data_type": "ID", "max_length": 2, "required": "O", "repeating": False, "table": "0038", "description": "A=Some but not all results, CA=Canceled, CM=Completed, DC=Discontinued, IP=In Process, SC=Scheduled."},
            {"position": 6, "name": "Response Flag", "data_type": "ID", "max_length": 1, "required": "O", "repeating": False, "table": "0121", "description": "E=Report exceptions, R=Same as E with replacements, D=Detailed, F=Full (all results)."},
            {"position": 7, "name": "Quantity/Timing", "data_type": "TQ", "max_length": 200, "required": "B", "repeating": True, "table": None, "description": "DEPRECATED in v2.5+. Use TQ1/TQ2 segments."},
            {"position": 8, "name": "Parent Order", "data_type": "EIP", "max_length": 200, "required": "O", "repeating": False, "table": None, "description": "Links to parent order for child orders."},
            {"position": 9, "name": "Date/Time of Transaction", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time the order event occurred."},
            {"position": 10, "name": "Entered By", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Person who entered the order."},
            {"position": 11, "name": "Verified By", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Person who verified the order."},
            {"position": 12, "name": "Ordering Provider", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Physician who ordered the procedure. Maps to DICOM (0008,0090) Referring Physician and (0032,1032) Requesting Physician."},
            {"position": 13, "name": "Enterer's Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Location where the order was entered."},
            {"position": 14, "name": "Call Back Phone Number", "data_type": "XTN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Call-back number for the order."},
            {"position": 15, "name": "Order Effective Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "When the order becomes effective."},
            {"position": 16, "name": "Order Control Code Reason", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Reason for the order control action."},
            {"position": 17, "name": "Entering Organization", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Organization that entered the order."},
            {"position": 18, "name": "Entering Device", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Device used to enter the order."},
            {"position": 19, "name": "Action By", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Person responsible for the action."},
        ],
        "notes": "ORC-1 (Order Control) is the most important field — it determines the intent of the message. ORC-2/ORC-3 together link placer and filler orders. In radiology: ORC-2 is the CPOE order number, ORC-3 is the RIS accession number.",
    },

    "OBR": {
        "name": "Observation Request",
        "description": "Contains information about an observation/test/procedure request.",
        "fields": [
            {"position": 1, "name": "Set ID - OBR", "data_type": "SI", "max_length": 4, "required": "O", "repeating": False, "table": None, "description": "Sequence number for multiple OBR segments."},
            {"position": 2, "name": "Placer Order Number", "data_type": "EI", "max_length": 427, "required": "C", "repeating": False, "table": None, "description": "Order number from ordering system. Should match ORC-2."},
            {"position": 3, "name": "Filler Order Number", "data_type": "EI", "max_length": 427, "required": "C", "repeating": False, "table": None, "description": "Order number from filling system. Should match ORC-3. Maps to DICOM Accession Number."},
            {"position": 4, "name": "Universal Service Identifier", "data_type": "CE", "max_length": 250, "required": "R", "repeating": False, "table": None, "description": "Identifies the observation/procedure. Format: Code^Description^Coding System. Example: 'CTABD^CT ABDOMEN^L' or '71046^XR CHEST 2V^CPT'."},
            {"position": 5, "name": "Priority", "data_type": "ID", "max_length": 2, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use OBR-27 or TQ1. S=Stat, A=ASAP, R=Routine, P=Pre-op, T=Timing critical."},
            {"position": 6, "name": "Requested Date/Time", "data_type": "TS", "max_length": 26, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use OBR-27 or TQ1."},
            {"position": 7, "name": "Observation Date/Time", "data_type": "TS", "max_length": 26, "required": "C", "repeating": False, "table": None, "description": "Clinically relevant date/time of the observation. For imaging: exam date/time. Maps to DICOM Study Date/Time."},
            {"position": 8, "name": "Observation End Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "End date/time if the observation spans a period."},
            {"position": 9, "name": "Collection Volume", "data_type": "CQ", "max_length": 20, "required": "O", "repeating": False, "table": None, "description": "Volume of specimen collected. Not used for imaging."},
            {"position": 10, "name": "Collector Identifier", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Person who collected the specimen."},
            {"position": 11, "name": "Specimen Action Code", "data_type": "ID", "max_length": 1, "required": "O", "repeating": False, "table": "0065", "description": "Action for specimen (Add, Generate, Pending, etc.)."},
            {"position": 12, "name": "Danger Code", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Danger associated with specimen/patient."},
            {"position": 13, "name": "Relevant Clinical Information", "data_type": "ST", "max_length": 300, "required": "O", "repeating": False, "table": None, "description": "Clinical history/indication. Maps to DICOM (0010,21B0) Additional Patient History. Critical for radiologist interpretation."},
            {"position": 14, "name": "Specimen Received Date/Time", "data_type": "TS", "max_length": 26, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED."},
            {"position": 15, "name": "Specimen Source", "data_type": "SPS", "max_length": 300, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use SPM segment."},
            {"position": 16, "name": "Ordering Provider", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Physician who ordered the test. Maps to DICOM (0008,0090) and (0032,1032)."},
            {"position": 17, "name": "Order Callback Phone Number", "data_type": "XTN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Phone number for callbacks about this order."},
            {"position": 18, "name": "Placer Field 1", "data_type": "ST", "max_length": 60, "required": "O", "repeating": False, "table": None, "description": "Placer-defined text field."},
            {"position": 19, "name": "Placer Field 2", "data_type": "ST", "max_length": 60, "required": "O", "repeating": False, "table": None, "description": "Placer-defined text field."},
            {"position": 20, "name": "Filler Field 1", "data_type": "ST", "max_length": 60, "required": "O", "repeating": False, "table": None, "description": "Filler-defined text field."},
            {"position": 21, "name": "Filler Field 2", "data_type": "ST", "max_length": 60, "required": "O", "repeating": False, "table": None, "description": "Filler-defined text field."},
            {"position": 22, "name": "Results Rpt/Status Chng - Date/Time", "data_type": "TS", "max_length": 26, "required": "C", "repeating": False, "table": None, "description": "Date/time results were reported or status changed."},
            {"position": 23, "name": "Charge to Practice", "data_type": "MOC", "max_length": 40, "required": "O", "repeating": False, "table": None, "description": "Charge information."},
            {"position": 24, "name": "Diagnostic Serv Sect ID", "data_type": "ID", "max_length": 10, "required": "O", "repeating": False, "table": "0074", "description": "Department performing the test. RAD=Radiology, LAB=Laboratory, CAR=Cardiology, etc."},
            {"position": 25, "name": "Result Status", "data_type": "ID", "max_length": 1, "required": "C", "repeating": False, "table": "0123", "description": "O=Order received, I=In process, S=Scheduled, A=Some results, P=Preliminary, C=Correction, R=Results stored, F=Final, X=Canceled."},
            {"position": 26, "name": "Parent Result", "data_type": "PRL", "max_length": 400, "required": "O", "repeating": False, "table": None, "description": "Links to parent result."},
            {"position": 27, "name": "Quantity/Timing", "data_type": "TQ", "max_length": 200, "required": "B", "repeating": True, "table": None, "description": "DEPRECATED. Use TQ1/TQ2. Contains priority, start date/time, etc."},
            {"position": 28, "name": "Result Copies To", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Physicians who should receive copies of the results. Maps to 'CC' doctors on radiology reports."},
            {"position": 29, "name": "Parent Number", "data_type": "EIP", "max_length": 200, "required": "O", "repeating": False, "table": None, "description": "Parent order number."},
            {"position": 30, "name": "Transportation Mode", "data_type": "ID", "max_length": 20, "required": "O", "repeating": False, "table": "0124", "description": "How the patient is transported (CART, PORT=portable, WALK, WHLC=wheelchair)."},
            {"position": 31, "name": "Reason for Study", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Clinical reason/indication for the study. ICD codes often placed here."},
            {"position": 32, "name": "Principal Result Interpreter", "data_type": "NDL", "max_length": 200, "required": "O", "repeating": False, "table": None, "description": "Interpreting physician. For radiology: the reading radiologist."},
            {"position": 33, "name": "Assistant Result Interpreter", "data_type": "NDL", "max_length": 200, "required": "O", "repeating": True, "table": None, "description": "Co-reading physician."},
            {"position": 34, "name": "Technician", "data_type": "NDL", "max_length": 200, "required": "O", "repeating": True, "table": None, "description": "Technologist who performed the exam."},
            {"position": 35, "name": "Transcriptionist", "data_type": "NDL", "max_length": 200, "required": "O", "repeating": True, "table": None, "description": "Person who transcribed the results."},
            {"position": 36, "name": "Scheduled Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Scheduled date/time of the procedure."},
            {"position": 44, "name": "Procedure Code", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0088", "description": "CPT or institutional procedure code."},
            {"position": 45, "name": "Procedure Code Modifier", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": "0340", "description": "CPT modifier codes."},
        ],
        "notes": "OBR is the workhorse segment for orders and results. OBR-4 identifies WHAT is being ordered. OBR-25 tracks the order lifecycle. In radiology ORU messages, OBR-32 identifies the reading radiologist. OBR-13 (Clinical Info) is critical for appropriate imaging interpretation.",
    },

    "OBX": {
        "name": "Observation/Result",
        "description": "Contains a single observation/result.",
        "fields": [
            {"position": 1, "name": "Set ID - OBX", "data_type": "SI", "max_length": 4, "required": "O", "repeating": False, "table": None, "description": "Sequence number within the OBR group."},
            {"position": 2, "name": "Value Type", "data_type": "ID", "max_length": 3, "required": "C", "repeating": False, "table": "0125", "description": "Data type of OBX-5. TX=Text, FT=Formatted Text, CE=Coded Entry, NM=Numeric, ST=String, ED=Encapsulated Data, RP=Reference Pointer."},
            {"position": 3, "name": "Observation Identifier", "data_type": "CE", "max_length": 250, "required": "R", "repeating": False, "table": None, "description": "Identifies what is being observed. Format: Code^Description^Coding System. Example: '&GDT^Radiology Report^L'."},
            {"position": 4, "name": "Observation Sub-ID", "data_type": "ST", "max_length": 20, "required": "C", "repeating": False, "table": None, "description": "Distinguishes multiple OBX segments with the same Observation Identifier."},
            {"position": 5, "name": "Observation Value", "data_type": "varies", "max_length": 99999, "required": "C", "repeating": True, "table": None, "description": "The actual result/value. Data type specified by OBX-2. For radiology reports: the report text (FT or TX type). For PDF reports: base64-encoded content (ED type)."},
            {"position": 6, "name": "Units", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Units of measurement for numeric results."},
            {"position": 7, "name": "References Range", "data_type": "ST", "max_length": 60, "required": "O", "repeating": False, "table": None, "description": "Normal range for the observation."},
            {"position": 8, "name": "Abnormal Flags", "data_type": "IS", "max_length": 5, "required": "O", "repeating": True, "table": "0078", "description": "L=Low, H=High, LL=Critical Low, HH=Critical High, N=Normal, A=Abnormal, AA=Very Abnormal."},
            {"position": 9, "name": "Probability", "data_type": "NM", "max_length": 5, "required": "O", "repeating": False, "table": None, "description": "Probability of the interpretation."},
            {"position": 10, "name": "Nature of Abnormal Test", "data_type": "ID", "max_length": 2, "required": "O", "repeating": True, "table": "0080", "description": "A=Age-based, N=None, R=Race-based, S=Sex-based."},
            {"position": 11, "name": "Observation Result Status", "data_type": "ID", "max_length": 1, "required": "R", "repeating": False, "table": "0085", "description": "C=Correction, D=Delete, F=Final, I=In process, P=Preliminary, R=Result entered, S=Partial, X=Cannot obtain, W=Original posted as wrong."},
            {"position": 12, "name": "Effective Date of Reference Range", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date reference range became effective."},
            {"position": 13, "name": "User Defined Access Checks", "data_type": "ST", "max_length": 20, "required": "O", "repeating": False, "table": None, "description": "Access level for this result."},
            {"position": 14, "name": "Date/Time of the Observation", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time of the observation. May differ per OBX within the same OBR."},
            {"position": 15, "name": "Producer's ID", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": None, "description": "Identifies the observer/producer of the result."},
            {"position": 16, "name": "Responsible Observer", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Person responsible for the observation."},
            {"position": 17, "name": "Observation Method", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Method used for the observation."},
        ],
        "notes": "OBX is the result segment. For radiology reports, OBX-2 is typically 'FT' (Formatted Text) or 'TX' (Text), and OBX-5 contains the report body. For PDF reports, OBX-2 is 'ED' and OBX-5 contains the encapsulated data. OBX-11 status must be 'F' for final results. Multiple OBX segments per OBR allow structured results (e.g., separate impression, findings, clinical history).",
    },

    "DG1": {
        "name": "Diagnosis",
        "description": "Contains patient diagnosis information.",
        "fields": [
            {"position": 1, "name": "Set ID - DG1", "data_type": "SI", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "Diagnosis Coding Method", "data_type": "ID", "max_length": 2, "required": "B", "repeating": False, "table": "0053", "description": "DEPRECATED. Coding method now in DG1-3 coding system component."},
            {"position": 3, "name": "Diagnosis Code - DG1", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0051", "description": "Diagnosis code. Format: Code^Description^CodingSystem. Example: 'R10.9^Unspecified abdominal pain^I10'."},
            {"position": 4, "name": "Diagnosis Description", "data_type": "ST", "max_length": 40, "required": "B", "repeating": False, "table": None, "description": "DEPRECATED. Use DG1-3 description component."},
            {"position": 5, "name": "Diagnosis Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time of diagnosis."},
            {"position": 6, "name": "Diagnosis Type", "data_type": "IS", "max_length": 2, "required": "R", "repeating": False, "table": "0052", "description": "A=Admitting, W=Working, F=Final."},
            {"position": 7, "name": "Major Diagnostic Category", "data_type": "CE", "max_length": 250, "required": "B", "repeating": False, "table": "0118", "description": "DEPRECATED. Major diagnostic category."},
            {"position": 8, "name": "Diagnostic Related Group", "data_type": "CE", "max_length": 250, "required": "B", "repeating": False, "table": "0055", "description": "DEPRECATED. DRG."},
            {"position": 9, "name": "DRG Approval Indicator", "data_type": "ID", "max_length": 1, "required": "B", "repeating": False, "table": "0136", "description": "DEPRECATED."},
            {"position": 10, "name": "DRG Grouper Review Code", "data_type": "IS", "max_length": 2, "required": "B", "repeating": False, "table": "0056", "description": "DEPRECATED."},
            {"position": 15, "name": "Diagnosis Priority", "data_type": "ID", "max_length": 2, "required": "O", "repeating": False, "table": "0359", "description": "1=Primary, 2+=Secondary."},
            {"position": 16, "name": "Diagnosing Clinician", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Clinician who made the diagnosis."},
        ],
        "notes": "Critical for billing and clinical decision support. ICD-10-CM codes go in DG1-3. For imaging orders, diagnosis codes support medical necessity.",
    },

    "AL1": {
        "name": "Patient Allergy Information",
        "description": "Contains patient allergy information.",
        "fields": [
            {"position": 1, "name": "Set ID - AL1", "data_type": "SI", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "Allergen Type Code", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0127", "description": "DA=Drug Allergy, FA=Food Allergy, MA=Miscellaneous Allergy, MC=Miscellaneous Contraindication, EA=Environmental Allergy, LA=Latex Allergy."},
            {"position": 3, "name": "Allergen Code/Mnemonic/Description", "data_type": "CE", "max_length": 250, "required": "R", "repeating": False, "table": None, "description": "Identifies the allergen. Critical for contrast allergy screening."},
            {"position": 4, "name": "Allergy Severity Code", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0128", "description": "SV=Severe, MO=Moderate, MI=Mild, U=Unknown."},
            {"position": 5, "name": "Allergy Reaction Code", "data_type": "ST", "max_length": 15, "required": "O", "repeating": True, "table": None, "description": "Description of the reaction."},
            {"position": 6, "name": "Identification Date", "data_type": "DT", "max_length": 8, "required": "B", "repeating": False, "table": None, "description": "Date allergy was identified."},
        ],
        "notes": "Critical for imaging safety, especially contrast allergy screening. Repeat the AL1 segment for each allergy. Maps to DICOM (0010,2110) Allergies.",
    },

    "NK1": {
        "name": "Next of Kin/Associated Parties",
        "description": "Contains information about the patient's next of kin and other associated parties.",
        "fields": [
            {"position": 1, "name": "Set ID - NK1", "data_type": "SI", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "NK Name", "data_type": "XPN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Name of next of kin. XPN format."},
            {"position": 3, "name": "Relationship", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0063", "description": "SPO=Spouse, PAR=Parent, CHD=Child, SIB=Sibling, OTH=Other."},
            {"position": 4, "name": "Address", "data_type": "XAD", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Next of kin address."},
            {"position": 5, "name": "Phone Number", "data_type": "XTN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Next of kin phone number."},
            {"position": 7, "name": "Contact Role", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0131", "description": "E=Emergency Contact, N=Next of Kin, F=Federal Agency, S=State Agency, O=Other."},
        ],
        "notes": "Repeat NK1 segment for each next of kin. Important for emergency contacts.",
    },

    "IN1": {
        "name": "Insurance",
        "description": "Contains patient insurance information.",
        "fields": [
            {"position": 1, "name": "Set ID - IN1", "data_type": "SI", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Sequence number. 1=Primary, 2=Secondary, 3=Tertiary."},
            {"position": 2, "name": "Insurance Plan ID", "data_type": "CE", "max_length": 250, "required": "R", "repeating": False, "table": "0072", "description": "Insurance plan identifier."},
            {"position": 3, "name": "Insurance Company ID", "data_type": "CX", "max_length": 250, "required": "R", "repeating": True, "table": None, "description": "Insurance company identifier."},
            {"position": 4, "name": "Insurance Company Name", "data_type": "XON", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Name of the insurance company."},
            {"position": 5, "name": "Insurance Company Address", "data_type": "XAD", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Insurance company address."},
            {"position": 12, "name": "Plan Effective Date", "data_type": "DT", "max_length": 8, "required": "O", "repeating": False, "table": None, "description": "Date insurance plan became effective."},
            {"position": 13, "name": "Plan Expiration Date", "data_type": "DT", "max_length": 8, "required": "O", "repeating": False, "table": None, "description": "Date insurance plan expires."},
            {"position": 15, "name": "Plan Type", "data_type": "IS", "max_length": 3, "required": "O", "repeating": False, "table": "0086", "description": "Insurance plan type."},
            {"position": 16, "name": "Name of Insured", "data_type": "XPN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Name of the insured person (may be different from patient)."},
            {"position": 36, "name": "Policy Number", "data_type": "ST", "max_length": 15, "required": "O", "repeating": False, "table": None, "description": "Insurance policy number."},
            {"position": 49, "name": "Insured's ID Number", "data_type": "CX", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Insured's member ID number."},
        ],
        "notes": "Repeat IN1 for each insurance plan (primary, secondary, etc.). Important for prior authorization of imaging studies. Insurance verification is often required before high-cost imaging (CT, MRI, PET).",
    },

    "GT1": {
        "name": "Guarantor",
        "description": "Contains guarantor (person financially responsible) information.",
        "fields": [
            {"position": 1, "name": "Set ID - GT1", "data_type": "SI", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "Guarantor Number", "data_type": "CX", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Guarantor identifier."},
            {"position": 3, "name": "Guarantor Name", "data_type": "XPN", "max_length": 250, "required": "R", "repeating": True, "table": None, "description": "Guarantor's name."},
            {"position": 5, "name": "Guarantor Address", "data_type": "XAD", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Guarantor's address."},
            {"position": 6, "name": "Guarantor Ph Num - Home", "data_type": "XTN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Guarantor's phone."},
            {"position": 10, "name": "Guarantor Type", "data_type": "IS", "max_length": 2, "required": "O", "repeating": False, "table": "0068", "description": "Type of guarantor."},
            {"position": 11, "name": "Guarantor Relationship", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0063", "description": "Relationship of guarantor to patient."},
        ],
        "notes": "Guarantor is the person financially responsible. May be the patient or a third party.",
    },

    "TXA": {
        "name": "Transcription Document Header",
        "description": "Contains document management information for transcribed documents.",
        "fields": [
            {"position": 1, "name": "Set ID - TXA", "data_type": "SI", "max_length": 4, "required": "R", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "Document Type", "data_type": "IS", "max_length": 30, "required": "R", "repeating": False, "table": "0270", "description": "Type of document (e.g., 'RAD' for radiology report, 'DS' for discharge summary)."},
            {"position": 3, "name": "Document Content Presentation", "data_type": "ID", "max_length": 2, "required": "C", "repeating": False, "table": "0191", "description": "AP=Application, FT=Formatted Text, TX=Text."},
            {"position": 4, "name": "Activity Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time of the document activity."},
            {"position": 5, "name": "Primary Activity Provider Code/Name", "data_type": "XCN", "max_length": 250, "required": "C", "repeating": True, "table": None, "description": "Provider creating the document (e.g., dictating radiologist)."},
            {"position": 6, "name": "Origination Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date/time document was originated."},
            {"position": 7, "name": "Transcription Date/Time", "data_type": "TS", "max_length": 26, "required": "C", "repeating": False, "table": None, "description": "Date/time of transcription."},
            {"position": 8, "name": "Edit Date/Time", "data_type": "TS", "max_length": 26, "required": "O", "repeating": True, "table": None, "description": "Date/time of last edit."},
            {"position": 9, "name": "Originator Code/Name", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Person who originated the document."},
            {"position": 12, "name": "Unique Document Number", "data_type": "EI", "max_length": 427, "required": "R", "repeating": False, "table": None, "description": "Unique identifier for the document."},
            {"position": 13, "name": "Parent Document Number", "data_type": "EI", "max_length": 427, "required": "C", "repeating": False, "table": None, "description": "Parent document (for addenda/amendments)."},
            {"position": 17, "name": "Document Completion Status", "data_type": "ID", "max_length": 2, "required": "R", "repeating": False, "table": "0271", "description": "AU=Authenticated, DI=Dictated, DO=Documented, IN=Incomplete, IP=In Progress, PA=Pre-authenticated, LA=Legally Authenticated."},
            {"position": 22, "name": "Authentication Person/Time Stamp", "data_type": "PPN", "max_length": 250, "required": "C", "repeating": True, "table": None, "description": "Person who authenticated (signed) the document and when."},
        ],
        "notes": "Used in MDM (Medical Document Management) messages for report distribution. In radiology: TXA carries the report header while OBX segments carry the report body. TXA-17 status is critical — only 'AU' or 'LA' documents should be treated as final.",
    },

    "FT1": {
        "name": "Financial Transaction",
        "description": "Contains financial transaction information.",
        "fields": [
            {"position": 1, "name": "Set ID - FT1", "data_type": "SI", "max_length": 4, "required": "O", "repeating": False, "table": None, "description": "Sequence number."},
            {"position": 2, "name": "Transaction ID", "data_type": "ST", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Transaction identifier."},
            {"position": 3, "name": "Transaction Batch ID", "data_type": "ST", "max_length": 10, "required": "O", "repeating": False, "table": None, "description": "Batch identifier."},
            {"position": 4, "name": "Transaction Date", "data_type": "DR", "max_length": 53, "required": "R", "repeating": False, "table": None, "description": "Date of the financial transaction."},
            {"position": 5, "name": "Transaction Posting Date", "data_type": "TS", "max_length": 26, "required": "O", "repeating": False, "table": None, "description": "Date transaction was posted."},
            {"position": 6, "name": "Transaction Type", "data_type": "IS", "max_length": 8, "required": "R", "repeating": False, "table": "0017", "description": "CG=Charge, CD=Credit, PY=Payment, AJ=Adjustment."},
            {"position": 7, "name": "Transaction Code", "data_type": "CE", "max_length": 250, "required": "R", "repeating": False, "table": "0132", "description": "Code for the transaction (CPT code for imaging charges)."},
            {"position": 10, "name": "Transaction Quantity", "data_type": "NM", "max_length": 6, "required": "O", "repeating": False, "table": None, "description": "Quantity of the transaction."},
            {"position": 11, "name": "Transaction Amount - Extended", "data_type": "CP", "max_length": 12, "required": "O", "repeating": False, "table": None, "description": "Extended amount."},
            {"position": 16, "name": "Assigned Patient Location", "data_type": "PL", "max_length": 80, "required": "O", "repeating": False, "table": None, "description": "Patient location at time of charge."},
            {"position": 19, "name": "Diagnosis Code - FT1", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": "0051", "description": "Diagnosis code associated with the charge. ICD-10 code."},
            {"position": 20, "name": "Performed By Code", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Provider who performed the service."},
            {"position": 21, "name": "Ordered By Code", "data_type": "XCN", "max_length": 250, "required": "O", "repeating": True, "table": None, "description": "Provider who ordered the service."},
            {"position": 25, "name": "Procedure Code", "data_type": "CE", "max_length": 250, "required": "O", "repeating": False, "table": "0088", "description": "CPT procedure code for billing."},
            {"position": 26, "name": "Procedure Code Modifier", "data_type": "CE", "max_length": 250, "required": "O", "repeating": True, "table": "0340", "description": "CPT modifier(s)."},
        ],
        "notes": "Used in DFT (Detailed Financial Transaction) messages. In radiology, FT1 carries CPT codes for imaging procedures. Important for revenue cycle management.",
    },
}


# ---------------------------------------------------------------
# HL7 Table Values (commonly referenced)
# ---------------------------------------------------------------
HL7_TABLES: dict[str, dict] = {
    "0001": {
        "name": "Administrative Sex",
        "values": {
            "F": "Female",
            "M": "Male",
            "O": "Other",
            "U": "Unknown",
            "A": "Ambiguous",
            "N": "Not applicable",
        },
    },
    "0002": {
        "name": "Marital Status",
        "values": {
            "A": "Separated",
            "D": "Divorced",
            "M": "Married",
            "S": "Single",
            "W": "Widowed",
            "C": "Common law",
            "G": "Living together",
            "P": "Domestic partner",
            "R": "Registered domestic partner",
            "E": "Legally Separated",
            "N": "Annulled",
            "I": "Interlocutory",
            "B": "Unmarried",
            "T": "Unreported",
            "U": "Unknown",
        },
    },
    "0003": {
        "name": "Event Type",
        "values": {
            "A01": "Admit/Visit Notification",
            "A02": "Transfer a Patient",
            "A03": "Discharge/End Visit",
            "A04": "Register a Patient",
            "A05": "Pre-Admit a Patient",
            "A06": "Change an Outpatient to an Inpatient",
            "A07": "Change an Inpatient to an Outpatient",
            "A08": "Update Patient Information",
            "A09": "Patient Departing - Tracking",
            "A10": "Patient Arriving - Tracking",
            "A11": "Cancel Admit/Visit Notification",
            "A12": "Cancel Transfer",
            "A13": "Cancel Discharge/End Visit",
            "A14": "Pending Admit",
            "A15": "Pending Transfer",
            "A16": "Pending Discharge",
            "A17": "Swap Patients",
            "A18": "Merge Patient Information",
            "A19": "Patient Query",
            "A20": "Bed Status Update",
            "A21": "Patient Goes on a Leave of Absence",
            "A22": "Patient Returns from a Leave of Absence",
            "A23": "Delete a Patient Record",
            "A24": "Link Patient Information",
            "A25": "Cancel Pending Discharge",
            "A26": "Cancel Pending Transfer",
            "A27": "Cancel Pending Admit",
            "A28": "Add Person Information",
            "A29": "Delete Person Information",
            "A30": "Merge Person Information",
            "A31": "Update Person Information",
            "A34": "Merge Patient Information - Patient ID Only",
            "A35": "Merge Patient Information - Account Number Only",
            "A36": "Merge Patient Information - Patient ID & Account Number",
            "A37": "Unlink Patient Information",
            "A38": "Cancel Pre-Admit",
            "A39": "Merge Person - Patient ID",
            "A40": "Merge Patient - Patient Identifier List",
            "A41": "Merge Account - Patient Account Number",
            "A44": "Move Account Information - Patient Account Number",
            "A45": "Move Visit Information - Visit Number",
            "A47": "Change Patient Identifier List",
            "A54": "Change Attending Doctor",
            "A60": "Update Allergy Information",
        },
    },
    "0004": {
        "name": "Patient Class",
        "values": {
            "E": "Emergency",
            "I": "Inpatient",
            "O": "Outpatient",
            "P": "Preadmit",
            "R": "Recurring patient",
            "B": "Obstetrics",
            "C": "Commercial Account",
            "N": "Not Applicable",
            "U": "Unknown",
        },
    },
    "0007": {
        "name": "Admission Type",
        "values": {
            "A": "Accident",
            "E": "Emergency",
            "L": "Labor and Delivery",
            "R": "Routine",
            "N": "Newborn (Birth in healthcare facility)",
            "U": "Urgent",
            "C": "Elective",
        },
    },
    "0038": {
        "name": "Order Status",
        "values": {
            "A": "Some, but not all, results available",
            "CA": "Order was canceled",
            "CM": "Order is completed",
            "DC": "Order was discontinued",
            "ER": "Error, order not found",
            "HD": "Order is on hold",
            "IP": "In process, unspecified",
            "RP": "Order has been replaced",
            "SC": "In process, scheduled",
        },
    },
    "0052": {
        "name": "Diagnosis Type",
        "values": {
            "A": "Admitting",
            "W": "Working",
            "F": "Final",
        },
    },
    "0062": {
        "name": "Event Reason",
        "values": {
            "01": "Patient request",
            "02": "Physician/health practitioner order",
            "03": "Census management",
            "O": "Other",
            "U": "Unknown",
        },
    },
    "0063": {
        "name": "Relationship",
        "values": {
            "SEL": "Self",
            "SPO": "Spouse",
            "DOM": "Life partner",
            "CHD": "Child",
            "GCH": "Grandchild",
            "NCH": "Natural child",
            "SCH": "Stepchild",
            "FCH": "Foster child",
            "DEP": "Handicapped dependent",
            "WRD": "Ward of the court",
            "PAR": "Parent",
            "MTH": "Mother",
            "FTH": "Father",
            "CGV": "Care giver",
            "GRD": "Guardian",
            "SIB": "Sibling",
            "BRO": "Brother",
            "SIS": "Sister",
            "FND": "Friend",
            "OAD": "Other adult",
            "EME": "Employee",
            "EMR": "Employer",
            "ASC": "Associate",
            "EMC": "Emergency contact",
            "OWN": "Owner",
            "TRA": "Trainer",
            "MGR": "Manager",
            "NON": "None",
            "UNK": "Unknown",
            "OTH": "Other",
        },
    },
    "0074": {
        "name": "Diagnostic Service Section ID",
        "values": {
            "AU": "Audiology",
            "BG": "Blood Gases",
            "BLB": "Blood Bank",
            "CG": "Cytogenetics",
            "CH": "Chemistry",
            "CP": "Cytopathology",
            "CT": "CAT Scan",
            "CTH": "Cardiac Catheterization",
            "CUS": "Cardiac Ultrasound",
            "EC": "Electrocardiac (ECG/EKG)",
            "EN": "Electroneuro (EEG/EMG)",
            "GE": "Genetics",
            "HM": "Hematology",
            "ICU": "Bedside ICU Monitoring",
            "IMM": "Immunology",
            "LAB": "Laboratory",
            "MB": "Microbiology",
            "MCB": "Mycobacteriology",
            "MYC": "Mycology",
            "NMR": "Nuclear Magnetic Resonance",
            "NMS": "Nuclear Medicine Scan",
            "NRS": "Nursing Service Measures",
            "OT": "Occupational Therapy",
            "OTH": "Other",
            "OUS": "OB Ultrasound",
            "PF": "Pulmonary Function",
            "PHR": "Pharmacy",
            "PHY": "Physician",
            "PT": "Physical Therapy",
            "RAD": "Radiology",
            "RC": "Respiratory Care",
            "RT": "Radiation Therapy",
            "RUS": "Radiology Ultrasound",
            "RX": "Radiograph",
            "SP": "Surgical Pathology",
            "SR": "Serology",
            "TX": "Toxicology",
            "URN": "Urinalysis",
            "VR": "Virology",
            "VUS": "Vascular Ultrasound",
            "XRC": "Cineradiograph",
        },
    },
    "0076": {
        "name": "Message Type",
        "values": {
            "ACK": "General acknowledgment message",
            "ADT": "ADT message",
            "BAR": "Add/change billing account",
            "DFT": "Detail financial transactions",
            "MDM": "Medical document management",
            "MFN": "Master files notification",
            "OML": "Laboratory order message",
            "ORM": "Pharmacy/treatment order message",
            "ORU": "Unsolicited observation message",
            "QRY": "Query (original mode)",
            "RAS": "Pharmacy/treatment administration",
            "RDE": "Pharmacy/treatment encoded order",
            "RDS": "Pharmacy/treatment dispense",
            "RGV": "Pharmacy/treatment give",
            "SIU": "Schedule information unsolicited",
            "SRM": "Schedule request message",
        },
    },
    "0078": {
        "name": "Abnormal Flags",
        "values": {
            "L": "Below low normal",
            "H": "Above high normal",
            "LL": "Below lower panic limits",
            "HH": "Above upper panic limits",
            "<": "Below absolute low-off instrument scale",
            ">": "Above absolute high-off instrument scale",
            "N": "Normal",
            "A": "Abnormal",
            "AA": "Very abnormal",
            "null": "No range defined, or normal ranges don't apply",
            "U": "Significant change up",
            "D": "Significant change down",
            "B": "Better",
            "W": "Worse",
            "S": "Susceptible",
            "R": "Resistant",
            "I": "Intermediate",
            "MS": "Moderately susceptible",
            "VS": "Very susceptible",
        },
    },
    "0085": {
        "name": "Observation Result Status",
        "values": {
            "C": "Record coming over is a correction and thus replaces a final result",
            "D": "Deletes the OBX record",
            "F": "Final results (can only be changed with a corrected result)",
            "I": "Specimen in lab; results pending",
            "N": "Not asked; used to affirmatively document that the observation identified in the OBX was not sought when the universal service ID in OBR-4 implies that it would be sought",
            "O": "Order detail description only (no result)",
            "P": "Preliminary results",
            "R": "Results entered -- not verified",
            "S": "Partial results",
            "U": "Results status change to final without retransmitting results already sent as 'preliminary'",
            "W": "Post original as wrong (e.g., transmitted for wrong patient)",
            "X": "Results cannot be obtained for this observation",
        },
    },
    "0103": {
        "name": "Processing ID",
        "values": {
            "D": "Debugging",
            "P": "Production",
            "T": "Training",
        },
    },
    "0104": {
        "name": "Version ID",
        "values": {
            "2.0": "Release 2.0 (September 1988)",
            "2.1": "Release 2.1 (March 1990)",
            "2.2": "Release 2.2 (December 1994)",
            "2.3": "Release 2.3 (March 1997)",
            "2.3.1": "Release 2.3.1 (May 1999)",
            "2.4": "Release 2.4 (November 2000)",
            "2.5": "Release 2.5 (June 2003)",
            "2.5.1": "Release 2.5.1 (January 2007)",
            "2.6": "Release 2.6 (October 2007)",
            "2.7": "Release 2.7 (November 2010)",
            "2.7.1": "Release 2.7.1 (July 2012)",
            "2.8": "Release 2.8 (November 2013)",
            "2.8.1": "Release 2.8.1 (April 2014)",
            "2.8.2": "Release 2.8.2 (May 2015)",
            "2.9": "Release 2.9 (December 2019)",
        },
    },
    "0119": {
        "name": "Order Control Codes",
        "values": {
            "NW": "New order/service",
            "OK": "Order/service accepted & OK",
            "UA": "Unable to accept order/service",
            "CA": "Cancel order/service request",
            "OC": "Order/service canceled",
            "CR": "Canceled as requested",
            "UC": "Unable to cancel",
            "DC": "Discontinue order/service request",
            "OD": "Order/service discontinued",
            "DR": "Discontinued as requested",
            "UD": "Unable to discontinue",
            "HD": "Hold order request",
            "OH": "Order/service held",
            "UH": "Unable to put on hold",
            "RL": "Release previous hold",
            "OE": "Order/service released",
            "OR": "Released as requested",
            "UR": "Unable to release",
            "SC": "Status changed",
            "SN": "Send order/service number",
            "SS": "Send order/service status request",
            "SR": "Response to send order/service status request",
            "XO": "Change order/service request",
            "XX": "Order/service changed, unsol.",
            "UX": "Unable to change",
            "XR": "Changed as requested",
            "RE": "Observations/Performed Service to follow",
            "RR": "Request received",
            "FU": "Order/service refilled, unsolicited",
            "RF": "Refill order/service request",
            "AF": "Order/service refill request approval",
            "DF": "Order/service refill request denied",
            "PA": "Parent order/service",
            "CH": "Child order/service",
            "RU": "Replaced unsolicited",
            "RO": "Replacement order",
            "RP": "Order/service replace request",
            "RQ": "Replaced as requested",
            "UM": "Unable to replace",
            "DE": "Data errors",
        },
    },
    "0123": {
        "name": "Result Status",
        "values": {
            "O": "Order received; specimen not yet received",
            "I": "No results available; specimen received, procedure incomplete",
            "S": "No results available; procedure scheduled, but not done",
            "A": "Some, but not all, results available",
            "P": "Preliminary: A verified early result is available, final results not yet obtained",
            "C": "Correction to results",
            "R": "Results stored; not yet verified",
            "F": "Final results; results stored and verified",
            "X": "No results available; Order canceled",
            "Y": "No order on record for this test",
            "Z": "No record of this patient",
        },
    },
    "0125": {
        "name": "Value Type",
        "values": {
            "AD": "Address",
            "CE": "Coded Entry",
            "CF": "Coded Element With Formatted Values",
            "CK": "Composite ID With Check Digit",
            "CN": "Composite ID And Name",
            "CP": "Composite Price",
            "CWE": "Coded with Exceptions",
            "CX": "Extended Composite ID with Check Digit",
            "DT": "Date",
            "ED": "Encapsulated Data",
            "FT": "Formatted Text",
            "MO": "Money",
            "NM": "Numeric",
            "PN": "Person Name",
            "RP": "Reference Pointer",
            "SN": "Structured Numeric",
            "ST": "String Data",
            "TM": "Time",
            "TN": "Telephone Number",
            "TS": "Time Stamp",
            "TX": "Text Data",
            "XAD": "Extended Address",
            "XCN": "Extended Composite Name and ID for Organizations",
            "XON": "Extended Composite Name and ID for Organizations",
            "XPN": "Extended Person Name",
            "XTN": "Extended Telecommunication Number",
        },
    },
    "0155": {
        "name": "Accept/Application Acknowledgment Conditions",
        "values": {
            "AL": "Always",
            "NE": "Never",
            "ER": "Error/reject conditions only",
            "SU": "Successful completion only",
        },
    },
    "0190": {
        "name": "Address Type",
        "values": {
            "B": "Firm/Business",
            "BA": "Bad address",
            "BDL": "Birth delivery location",
            "BR": "Residence at birth",
            "C": "Current or Temporary",
            "F": "Country Of Origin",
            "H": "Home",
            "L": "Legal Address",
            "M": "Mailing",
            "N": "Birth (nee)",
            "O": "Office/Business",
            "P": "Permanent",
            "RH": "Registry home",
            "S": "Service Location",
        },
    },
    "0203": {
        "name": "Identifier Type",
        "values": {
            "AM": "American Express",
            "AN": "Account number",
            "ANC": "Account number Creditor",
            "AND": "Account number debitor",
            "ANON": "Anonymous identifier",
            "BA": "Bank Account Number",
            "BR": "Birth registry number",
            "DI": "Diner's Club card",
            "DL": "Driver's license number",
            "DN": "Doctor number",
            "DR": "Donor Registration Number",
            "DS": "Discover Card",
            "EI": "Employee number",
            "EN": "Employer number",
            "FI": "Facility ID",
            "GI": "Guarantor internal identifier",
            "GN": "Guarantor external identifier",
            "HC": "Health Card Number",
            "JHN": "Jurisdictional health number (Canada)",
            "LN": "License number",
            "LR": "Local Registry ID",
            "MA": "Patient Medicaid number",
            "MB": "Member Number",
            "MC": "Patient's Medicare number",
            "MCD": "Practitioner Medicaid number",
            "MCN": "Microchip Number",
            "MCR": "Practitioner Medicare number",
            "MD": "Medical License number",
            "MI": "Military ID number",
            "MR": "Medical record number",
            "MRT": "Temporary Medical Record Number",
            "MS": "MasterCard",
            "NE": "National employer identifier",
            "NH": "National Health Plan Identifier",
            "NI": "National unique individual identifier",
            "NNxxx": "National Person Identifier where xxx = ISO 3166 country code",
            "NP": "Nurse practitioner number",
            "NPI": "National provider identifier",
            "OD": "Optometrist license number",
            "PA": "Physician Assistant number",
            "PCN": "Penitentiary/correctional institution Number",
            "PE": "Living Subject Enterprise Number",
            "PEN": "Pension Number",
            "PI": "Patient internal identifier",
            "PN": "Person number",
            "PNT": "Temporary Living Subject Number",
            "PPIN": "Medicare/CMS Performing Provider ID",
            "PRC": "Permanent Resident Card Number",
            "PRN": "Provider number",
            "PT": "Patient external identifier",
            "QA": "QA number",
            "RI": "Resource identifier",
            "RN": "Registered Nurse Number",
            "RPH": "Pharmacist license number",
            "RR": "Railroad Retirement number",
            "RRI": "Regional registry ID",
            "SL": "State license",
            "SN": "Subscriber Number",
            "SP": "Study Permit",
            "SR": "State registry ID",
            "SS": "Social Security number",
            "TAX": "Tax ID number",
            "TN": "Treaty Number/(Canada)",
            "U": "Unspecified identifier",
            "UPIN": "Medicare/CMS (formerly HCFA) Universal Physician ID",
            "VN": "Visit number",
            "VS": "VISA",
            "WC": "WIC identifier",
            "WCN": "Workers' Comp Number",
            "XX": "Organization identifier",
        },
    },
    "0271": {
        "name": "Document Completion Status",
        "values": {
            "AU": "Authenticated",
            "DI": "Dictated",
            "DO": "Documented",
            "IN": "Incomplete",
            "IP": "In Progress",
            "LA": "Legally Authenticated",
            "PA": "Pre-Authenticated",
        },
    },
    "0396": {
        "name": "Coding System",
        "values": {
            "99zzz": "Local general code (where z is an alphanumeric character)",
            "ACR": "American College of Radiology finding codes",
            "ANS+": "HL7 set of units of measure",
            "C4": "CPT-4",
            "C5": "CPT-5",
            "CAS": "Chemical abstract codes",
            "CD2": "CDT-2 Codes",
            "CDCA": "CDC Analyte Codes",
            "CDCM": "CDC Methods/Instruments Codes",
            "CDS": "CDC Surveillance",
            "I10": "ICD-10",
            "I10P": "ICD-10 Procedure Codes",
            "I9": "ICD-9",
            "I9C": "ICD-9CM",
            "I9CDX": "ICD-9CM Diagnosis codes",
            "I9CP": "ICD-9CM Procedure codes",
            "ISO+": "ISO 2955.83 (units of measure) with HL7 extensions",
            "L": "Local general code",
            "LN": "LOINC",
            "NPI": "National Provider Identifier",
            "SCT": "SNOMED CT",
            "SNM3": "SNOMED International",
            "UCUM": "UCUM code set for units of measure",
        },
    },
}


# ---------------------------------------------------------------
# Common HL7 Message Types and Trigger Events
# ---------------------------------------------------------------
HL7_MESSAGE_TYPES: dict[str, dict] = {
    "ADT^A01": {
        "name": "Admit/Visit Notification",
        "description": "Sent when a patient is admitted (inpatient) or begins a visit (outpatient/emergency).",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": ["PV2", "NK1", "AL1", "DG1", "IN1", "GT1"],
        "use_case": "Triggers creation of patient/visit in receiving systems. PACS, RIS, and departmental systems use this to create patient records.",
    },
    "ADT^A02": {
        "name": "Transfer a Patient",
        "description": "Sent when a patient is transferred from one location to another.",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": ["PV2"],
        "use_case": "Updates patient location in downstream systems. PV1-3 contains the new location; PV1-6 contains the prior location.",
    },
    "ADT^A03": {
        "name": "Discharge/End Visit",
        "description": "Sent when a patient is discharged (inpatient) or a visit ends (outpatient).",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": ["PV2", "DG1"],
        "use_case": "Closes the visit/encounter in receiving systems. PV1-45 contains the discharge date/time.",
    },
    "ADT^A04": {
        "name": "Register a Patient",
        "description": "Sent when an outpatient arrives and is registered (but not formally admitted).",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": ["NK1", "AL1", "DG1", "IN1"],
        "use_case": "Most common ADT event for outpatient imaging. Creates patient visit for outpatient encounters.",
    },
    "ADT^A08": {
        "name": "Update Patient Information",
        "description": "Sent when patient demographic information is updated.",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": ["NK1", "AL1", "DG1", "IN1"],
        "use_case": "Updates demographics in receiving systems. High volume event — many systems send A08 for any change including location, attending, or diagnosis updates.",
    },
    "ADT^A11": {
        "name": "Cancel Admit/Visit Notification",
        "description": "Sent to cancel a previously sent A01.",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": [],
        "use_case": "Reverses an admission. Receiving systems should revert the patient to their pre-admission state.",
    },
    "ADT^A13": {
        "name": "Cancel Discharge/End Visit",
        "description": "Sent to cancel a previously sent A03.",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": [],
        "use_case": "Reverses a discharge. Patient returns to their prior admitted/registered state.",
    },
    "ADT^A18": {
        "name": "Merge Patient Information",
        "description": "Sent when two patient records are merged (duplicate resolution).",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": [],
        "use_case": "Critical for duplicate patient management. The surviving MRN stays in PID-3; the merged-away MRN is in MRG-1.",
    },
    "ADT^A28": {
        "name": "Add Person Information",
        "description": "Sent to add person information without a visit context.",
        "required_segments": ["MSH", "EVN", "PID"],
        "optional_segments": ["NK1", "AL1", "IN1"],
        "use_case": "Creates a person record (MPI entry) without an associated visit. Pre-registration.",
    },
    "ADT^A31": {
        "name": "Update Person Information",
        "description": "Sent to update person information without visit context.",
        "required_segments": ["MSH", "EVN", "PID"],
        "optional_segments": ["NK1", "AL1"],
        "use_case": "Updates demographics at the person level (not visit-specific).",
    },
    "ADT^A34": {
        "name": "Merge Patient Information - Patient ID Only",
        "description": "Merges patient information at the patient identifier level only.",
        "required_segments": ["MSH", "EVN", "PID", "MRG"],
        "optional_segments": [],
        "use_case": "Merges two MRNs for the same patient. PACS must merge all studies from both MRNs. The merged-away MRN is in MRG-1.",
    },
    "ADT^A40": {
        "name": "Merge Patient - Patient Identifier List",
        "description": "Merges patient using the patient identifier list.",
        "required_segments": ["MSH", "EVN", "PID", "MRG", "PV1"],
        "optional_segments": [],
        "use_case": "More comprehensive merge event. Preferred over A34 in newer implementations.",
    },
    "ORM^O01": {
        "name": "Order Message",
        "description": "Sent to place, cancel, or modify an order.",
        "required_segments": ["MSH", "PID", "PV1", "ORC", "OBR"],
        "optional_segments": ["NK1", "AL1", "DG1", "IN1", "NTE"],
        "use_case": "The primary order message for radiology. ORC-1 determines the action (NW=new, CA=cancel, XO=change). OBR-4 identifies the procedure.",
    },
    "ORU^R01": {
        "name": "Unsolicited Observation Result",
        "description": "Sent to deliver results (observations) from the filler to the placer or interested parties.",
        "required_segments": ["MSH", "PID", "PV1", "ORC", "OBR", "OBX"],
        "optional_segments": ["NK1", "NTE"],
        "use_case": "THE results message. For radiology: carries dictated reports. OBR-25 indicates result status (P=Preliminary, F=Final, C=Corrected). OBX segments contain the report text.",
    },
    "ORM^O01_Cancel": {
        "name": "Order Cancellation",
        "description": "ORM^O01 with ORC-1=CA to cancel an existing order.",
        "required_segments": ["MSH", "PID", "PV1", "ORC", "OBR"],
        "optional_segments": [],
        "use_case": "Cancels a previously placed order. ORC-3 (Filler Order Number) identifies which order to cancel.",
    },
    "SIU^S12": {
        "name": "Notification of New Appointment Booking",
        "description": "Sent when a new appointment is scheduled.",
        "required_segments": ["MSH", "SCH", "PID", "PV1", "RGS", "AIS"],
        "optional_segments": ["AIG", "AIL", "AIP", "NTE"],
        "use_case": "Scheduling notification. Used for modality worklist population and resource management.",
    },
    "SIU^S14": {
        "name": "Notification of Appointment Modification",
        "description": "Sent when an existing appointment is modified.",
        "required_segments": ["MSH", "SCH", "PID", "PV1", "RGS", "AIS"],
        "optional_segments": [],
        "use_case": "Updates a previously scheduled appointment.",
    },
    "SIU^S15": {
        "name": "Notification of Appointment Cancellation",
        "description": "Sent when an appointment is canceled.",
        "required_segments": ["MSH", "SCH", "PID", "PV1", "RGS", "AIS"],
        "optional_segments": [],
        "use_case": "Cancels a previously scheduled appointment.",
    },
    "MDM^T01": {
        "name": "Original Document Notification",
        "description": "Sent when an original document is created.",
        "required_segments": ["MSH", "EVN", "PID", "PV1", "TXA"],
        "optional_segments": ["OBX", "NTE"],
        "use_case": "Notification only — no document content. Used when the content is available via query.",
    },
    "MDM^T02": {
        "name": "Original Document Notification and Content",
        "description": "Sent with original document notification AND the document content.",
        "required_segments": ["MSH", "EVN", "PID", "PV1", "TXA", "OBX"],
        "optional_segments": ["NTE"],
        "use_case": "Full document with content. OBX segments carry the document body. Common for radiology report distribution.",
    },
    "MDM^T11": {
        "name": "Document Cancel Notification",
        "description": "Sent when a document is canceled or retracted.",
        "required_segments": ["MSH", "EVN", "PID", "PV1", "TXA"],
        "optional_segments": [],
        "use_case": "Cancels a previously distributed document. Important for retracting incorrect reports.",
    },
    "DFT^P03": {
        "name": "Post Detail Financial Transactions",
        "description": "Sent to post financial transaction information.",
        "required_segments": ["MSH", "EVN", "PID", "PV1", "FT1"],
        "optional_segments": ["DG1", "IN1", "GT1"],
        "use_case": "Posts charges for imaging procedures. FT1 contains CPT codes and charge information.",
    },
    "BAR^P01": {
        "name": "Add Patient Accounts",
        "description": "Sent to add or update patient billing account information.",
        "required_segments": ["MSH", "EVN", "PID", "PV1"],
        "optional_segments": ["DG1", "IN1", "GT1", "FT1"],
        "use_case": "Opens/updates billing accounts. Often triggers insurance verification workflows.",
    },
    "ACK": {
        "name": "General Acknowledgment",
        "description": "Acknowledgment of a received message.",
        "required_segments": ["MSH", "MSA"],
        "optional_segments": ["ERR"],
        "use_case": "Sent in response to any message that requires acknowledgment. MSA-1 contains AA (Accept), AE (Application Error), or AR (Application Reject). MSA-2 references the original MSH-10.",
    },
}
